// Code generated by jm-sqlgen from schema.sql and queries.sql. DO NOT EDIT.

package notes_queries

import "core:testing"

import "jm:sqlite3"

@(private = "file")
Sqlgen_Set :: struct {
	name:   string,
	seed:   string,
	int_v:  i64,
	real_v: f64,
	text_v: string,
	blob_v: string,
	bool_v: bool,
	nulls:  bool,
}

// SQLGEN_SETS are the database states every query runs against: nothing at
// all, which empties aggregates and subqueries; every nullable column NULL;
// the extremes of each type; and each table alone, which leaves the other
// side of an outer join missing.
// low: note.pinned holds the base value, since note refused the set's own: CHECK constraint
// failed: pinned IN (0, 1).
// high: note.pinned holds the base value, since note refused the set's own: CHECK constraint
// failed: pinned IN (0, 1).
@(private = "file")
SQLGEN_SETS := [?]Sqlgen_Set {
	{
		name = "empty",
		seed = ``,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = false,
	},
	{
		name = "nulls",
		seed = `INSERT INTO "label"("note_id", "name")
VALUES (1, 'a');
INSERT INTO "note"("id", "body", "pinned", "score", "attachment")
VALUES (1, 'a', 1, 1.5, NULL);
`,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = true,
	},
	{
		name = "low",
		seed = `INSERT INTO "label"("note_id", "name")
VALUES (-9223372036854775808, '');
INSERT INTO "note"("id", "body", "pinned", "score", "attachment")
VALUES (-9223372036854775808, '', 1, -1.5, x'');
`,
		int_v = -9223372036854775808,
		real_v = -1.5,
		text_v = ``,
		blob_v = ``,
		bool_v = false,
		nulls = false,
	},
	{
		name = "high",
		seed = `INSERT INTO "label"("note_id", "name")
VALUES (9223372036854775807, 'zß€😀');
INSERT INTO "note"("id", "body", "pinned", "score", "attachment")
VALUES (9223372036854775807, 'zß€😀', 1, 1e+300, x'00ff');
`,
		int_v = 9223372036854775807,
		real_v = 1e+300,
		text_v = `zß€😀`,
		blob_v = "\x00\xff",
		bool_v = true,
		nulls = false,
	},
	{
		name = "only_label",
		seed = `INSERT INTO "label"("note_id", "name")
VALUES (1, 'a');
`,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = true,
	},
	{
		name = "only_note",
		seed = `INSERT INTO "note"("id", "body", "pinned", "score", "attachment")
VALUES (1, 'a', 1, 1.5, NULL);
`,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = true,
	},
}

// Each query runs in every data set through its generated proc, which
// checks every value it reads against the type it was generated with. check
// runs too, against the schema as SQLite holds it.
@(test)
sqlgen_queries_hold_their_types :: proc(t: ^testing.T) {
	context.allocator = context.temp_allocator
	for set in SQLGEN_SETS {
		db, err := sqlite3.open(sqlite3.MEMORY)
		if !testing.expectf(t, err == nil, "data set %s: open: %v", set.name, err) {
			return
		}
		defer sqlite3.close(&db)
		testing.expect_value(t, sqlite3.exec(db, #load("schema.sql", string)), nil)
		testing.expect_value(t, sqlite3.exec(db, set.seed), nil)
		testing.expect_value(t, check(db), nil)
		sqlgen_run(t, db, set)
	}
}

@(private = "file")
sqlgen_run :: proc(t: ^testing.T, db: sqlite3.Db, set: Sqlgen_Set) {
	{
		sqlgen_begin(t, db)
		_, _, err := note(db, sqlgen_int(set, i64))
		sqlgen_end(t, db, set, "note", err)
	}
	{
		sqlgen_begin(t, db)
		_, _, err := totals(db)
		sqlgen_end(t, db, set, "totals", err)
	}
	{
		sqlgen_begin(t, db)
		rows, err := labelled_open(db)
		if err == nil {
			for _ in labelled_next(&rows) {
			}
			err = labelled_close(&rows)
		}
		sqlgen_end(t, db, set, "labelled_open", err)
	}
	{
		sqlgen_begin(t, db)
		rows: Labelled_Rows
		if labelled(&rows, db) {
			for _ in labelled_next(&rows) {
			}
		}
		sqlgen_end(t, db, set, "labelled", rows.err)
	}
	{
		sqlgen_begin(t, db)
		_, err := labelled_all(db)
		sqlgen_end(t, db, set, "labelled_all", err)
	}
	{
		sqlgen_begin(t, db)
		_, err := add(db, set.text_v, sqlgen_maybe(transmute([]byte)set.blob_v, set.nulls))
		sqlgen_end(t, db, set, "add", err)
	}
	{
		sqlgen_begin(t, db)
		_, err := rescore(db, sqlgen_int(set, i64), sqlgen_real(set, f64))
		sqlgen_end(t, db, set, "rescore", err)
	}
	{
		sqlgen_begin(t, db)
		err := label(db, sqlgen_int(set, i64), set.text_v)
		sqlgen_end(t, db, set, "label", err)
	}
	{
		sqlgen_begin(t, db)
		_, err := unpin_all(db)
		sqlgen_end(t, db, set, "unpin_all", err)
	}
}

@(private = "file")
sqlgen_maybe :: proc(v: $T, null: bool) -> Maybe(T) {
	if null {
		return nil
	}
	return v
}

// sqlgen_int is the set's integer as T, held to T's range, so the extremes
// of the set are the extremes of each width.
@(private = "file")
sqlgen_int :: proc(set: Sqlgen_Set, $T: typeid) -> T {
	return T(clamp(set.int_v, i64(min(T)), i64(max(T))))
}

// sqlgen_real is the set's float as T, held to T's finite range.
@(private = "file")
sqlgen_real :: proc(set: Sqlgen_Set, $T: typeid) -> T {
	return T(clamp(set.real_v, -f64(max(T)), f64(max(T))))
}

@(private = "file")
sqlgen_begin :: proc(t: ^testing.T, db: sqlite3.Db) {
	testing.expect_value(t, sqlite3.exec(db, "SAVEPOINT sqlgen"), nil)
}

// sqlgen_end undoes what the query changed, and fails the test unless the
// query succeeded or a constraint the data set happens to break refused it.
// A STRICT column refusing a parameter's type is not such a constraint.
@(private = "file")
sqlgen_end :: proc(
	t: ^testing.T,
	db: sqlite3.Db,
	set: Sqlgen_Set,
	query: string,
	err: sqlite3.Error,
) {
	testing.expect_value(t, sqlite3.exec(db, "ROLLBACK TO sqlgen; RELEASE sqlgen"), nil)
	f, failed := err.(sqlite3.Fault)
	if !failed {
		return
	}
	broke_a_constraint := f.code == .Constraint && f.extended != sqlite3.CONSTRAINT_DATATYPE
	testing.expectf(t, broke_a_constraint, "data set %s: %s: %v: %s", set.name, query, f.code, f.text)
}
