// Code generated by jm-sqlgen from schema.sql and queries.sql. DO NOT EDIT.

package notes_queries

import "core:fmt"

import "jm:sqlite3"

// Editing either file without regenerating fails the build here.
#assert(
	#hash(#load("schema.sql", string), "fnv64a") == 0xfc84fb0914d8e592,
	"schema.sql changed: run jm-sqlgen",
)
#assert(
	#hash(#load("queries.sql", string), "fnv64a") == 0xb1c36999cfdd7ab6,
	"queries.sql changed: run jm-sqlgen",
)

@(private = "file")
NOTE_SQL :: `SELECT body, pinned AS "pinned: bool", score, attachment FROM note WHERE id = @id`

// Note_Row is a row of note. Text and blob fields are allocated in the
// allocator the query was given.
Note_Row :: struct {
	body:       string,
	pinned:     bool, // annotated, not inferred
	score:      f64,
	attachment: Maybe([]byte),
}

// The note with id, if there is one.
//
// note is :one in queries.sql.
note :: proc(
	db: sqlite3.Db,
	id: i64,
	allocator := context.allocator,
) -> (
	row: Note_Row,
	found: bool,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		NOTE_SQL,
		id,
		allocator = allocator,
	) or_return
	if sqlite3.next(&stmt) {
		found = true
		row.body = sqlite3.read_exact(&stmt, 0, string)
		row.pinned = sqlite3.read_exact(&stmt, 1, bool)
		row.score = sqlite3.read_exact(&stmt, 2, f64)
		row.attachment = sqlite3.read_exact_maybe(&stmt, 3, []byte)
		if stmt.err == nil && sqlite3.next(&stmt) {
			stmt.err = sqlite3.Fault {
				code = .Misuse,
				text = fmt.aprint("note is :one but returned a second row", allocator = allocator),
			}
		}
	}
	if err = sqlite3.finish(&stmt); err != nil {
		return {}, false, err
	}
	return
}

@(private = "file")
TOTALS_SQL :: `SELECT count(*) AS "notes: i64", sum(score) AS "score: Maybe(f64)" FROM note`

// Totals_Row is a row of totals. Text and blob fields are allocated in the
// allocator the query was given.
Totals_Row :: struct {
	notes: i64, // annotated, not inferred
	score: Maybe(f64), // annotated, not inferred
}

// How many notes there are and their summed score, which is NULL when
// there are none.
//
// totals is :one in queries.sql.
totals :: proc(
	db: sqlite3.Db,
	allocator := context.allocator,
) -> (
	row: Totals_Row,
	found: bool,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		TOTALS_SQL,
		allocator = allocator,
	) or_return
	if sqlite3.next(&stmt) {
		found = true
		row.notes = sqlite3.read_exact(&stmt, 0, i64)
		row.score = sqlite3.read_exact_maybe(&stmt, 1, f64)
		if stmt.err == nil && sqlite3.next(&stmt) {
			stmt.err = sqlite3.Fault {
				code = .Misuse,
				text = fmt.aprint("totals is :one but returned a second row", allocator = allocator),
			}
		}
	}
	if err = sqlite3.finish(&stmt); err != nil {
		return {}, false, err
	}
	return
}

@(private = "file")
LABELLED_SQL :: `SELECT n.id, n.body, l.name AS label
FROM note n LEFT JOIN label l ON l.note_id = n.id
ORDER BY n.id, l.name`

// Labelled_Row is a row of labelled. Text and blob fields are allocated in the
// allocator the query was given.
Labelled_Row :: struct {
	id:    i64,
	body:  string,
	label: Maybe(string), // Maybe: label is on the outer side of a join
}

// Each note with its labels, an unlabelled one once with no label.
//
// labelled is :many in queries.sql.
labelled :: proc(
	db: sqlite3.Db,
	allocator := context.allocator,
) -> (
	rows: Labelled_Rows,
	err: sqlite3.Error,
) {
	rows.stmt = sqlite3.query(
		db,
		LABELLED_SQL,
		allocator = allocator,
	) or_return
	return
}

// Labelled_Rows is the cursor labelled returns: step it with labelled_next and end it
// with labelled_finish, which returns what stopped it.
Labelled_Rows :: struct {
	stmt: sqlite3.Stmt,
}

// labelled_next reads the next row; ok is false at the end or on a failure.
labelled_next :: proc(rows: ^Labelled_Rows) -> (row: Labelled_Row, ok: bool) {
	if !sqlite3.next(&rows.stmt) {
		return
	}
	row.id = sqlite3.read_exact(&rows.stmt, 0, i64)
	row.body = sqlite3.read_exact(&rows.stmt, 1, string)
	row.label = sqlite3.read_exact_maybe(&rows.stmt, 2, string)
	return row, rows.stmt.err == nil
}

labelled_finish :: proc(rows: ^Labelled_Rows) -> sqlite3.Error {
	return sqlite3.finish(&rows.stmt)
}

@(private = "file")
ADD_SQL :: `INSERT INTO note(body, attachment) VALUES (@body, @attachment)`

// add is :last_id in queries.sql.
add :: proc(
	db: sqlite3.Db,
	body: string,
	attachment: Maybe([]byte),
	allocator := context.allocator,
) -> (
	n: i64,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		ADD_SQL,
		body,
		sqlite3.nullable(attachment),
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	sqlite3.finish(&stmt) or_return
	return sqlite3.last_id(db), nil
}

@(private = "file")
RESCORE_SQL :: `UPDATE note SET score = @score WHERE id = @id`

// rescore is :rows in queries.sql.
rescore :: proc(
	db: sqlite3.Db,
	id: i64,
	score: f64,
	allocator := context.allocator,
) -> (
	n: i64,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		RESCORE_SQL,
		score,
		id,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	sqlite3.finish(&stmt) or_return
	return sqlite3.changes(db), nil
}

@(private = "file")
LABEL_SQL :: `INSERT INTO label(note_id, name) VALUES (@note_id, @name) ON CONFLICT DO NOTHING`

// label is :exec in queries.sql.
label :: proc(
	db: sqlite3.Db,
	note_id: i64,
	name: string,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		LABEL_SQL,
		note_id,
		name,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

@(private = "file")
UNPIN_ALL_SQL :: `UPDATE note SET pinned = 0 WHERE pinned = 1`

// unpin_all is :rows in queries.sql.
unpin_all :: proc(
	db: sqlite3.Db,
	allocator := context.allocator,
) -> (
	n: i64,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		UNPIN_ALL_SQL,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	sqlite3.finish(&stmt) or_return
	return sqlite3.changes(db), nil
}

// check prepares every query against db and compares the parameters and
// columns each has there with those it was generated for, so a database
// whose schema has drifted from schema.sql fails when it is opened rather
// than when a query first runs.
check :: proc(db: sqlite3.Db, allocator := context.allocator) -> sqlite3.Error {
	sqlite3.check_statement(
		db,
		"note",
		NOTE_SQL,
		1,
		{"body", "pinned: bool", "score", "attachment"},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"totals",
		TOTALS_SQL,
		0,
		{"notes: i64", "score: Maybe(f64)"},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"labelled",
		LABELLED_SQL,
		0,
		{"id", "body", "label"},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"add",
		ADD_SQL,
		2,
		{},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"rescore",
		RESCORE_SQL,
		2,
		{},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"label",
		LABEL_SQL,
		2,
		{},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"unpin_all",
		UNPIN_ALL_SQL,
		0,
		{},
		allocator,
	) or_return
	return nil
}
