/*
Package fuzz is the jm:git suite for jm:fuzz: the promises the binding
makes, checked against generated sequences of operations rather than
generated bytes, because libgit2 parses and the wrapper sequences.

	report := fuzz.run({seed = 1, iterations = 2_000})

	sequence   any order of writes, adds, commits, pushes, fetches and pulls
	           across two clones of one hub agrees with a model that knows no
	           merges: pushes succeed exactly when the hub is behind, pulls
	           fast-forward exactly when the clone is and refuse over
	           uncommitted work, log is the history in order, status is what
	           the three trees say, ahead/behind is the arithmetic
	strings    a message, a path or a remote name comes back as it went in,
	           or the call refused it: nothing is silently cut or changed
	damaged    a repository with a corrupted HEAD, index, config or branch
	           opens or faults, and never takes the process down

Each case starts from a fresh hub with one commit and two clones of it,
all on local paths, so a run needs no network and a failure shrinks to the
shortest sequence that breaks the model.
*/
package git_fuzz

import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"

import harness "jm:fuzz"
import "jm:git"
import "jm:path"

SIG :: git.Signature{"Fuzz", "fuzz@example.com"}

// Clone is one working clone and what the model believes about it: the
// commits it has, and the three trees git keeps, as path to content.
Clone :: struct {
	name:      string,
	dir:       string,
	repo:      git.Repo,
	history:   [dynamic]string, // commit ids, oldest first
	files:     map[string]string, // the working tree
	staged:    map[string]string, // the index
	committed: map[string]string, // HEAD's tree
}

// World is one case's hub and two clones.
World :: struct {
	root:        string,
	hub:         string,
	hub_history: [dynamic]string,
	hub_files:   map[string]string,
	clones:      [2]Clone,
	branch:      string,
}

properties := []harness.Property(^World) {
	{"sequence", sequence},
	{"strings", strings_round_trip},
	{"damaged", damaged},
}

suite :: proc() -> harness.Suite(^World) {
	return harness.Suite(^World){name = "git", setup = setup, teardown = teardown, properties = properties}
}

// CORPUS is where this suite's regressions live, relative to the
// repository root.
CORPUS :: "git/fuzz/corpus"

run :: proc(opts := harness.Opts{}, allocator := context.allocator) -> harness.Report {
	return harness.run(suite(), opts, allocator)
}

// FIRST is the file every world starts with, so both clones have a
// commit and a branch to be on.
FIRST :: "README.md"

// setup makes a bare hub, clone a with one commit pushed to it, and clone
// b cloned from it, under a fresh temporary directory.
setup :: proc() -> (w: ^World, ok: bool) {
	w = new(World)
	root, terr := path.temp_dir("jm-git-fuzz-")
	if terr != nil {
		return w, false
	}
	w.root = root
	w.hub = path.join(root, "hub.git")
	hub, herr := git.init(w.hub, bare = true)
	if herr != nil {
		return w, false
	}
	git.close(&hub)

	a := &w.clones[0]
	a.name, a.dir = "a", path.join(root, "a")
	repo, ierr := git.init(a.dir)
	if ierr != nil {
		return w, false
	}
	a.repo = repo
	if path.write(path.join(a.dir, FIRST), "# fuzz\n") != nil {
		return w, false
	}
	a.files[FIRST] = "# fuzz\n"
	if git.add(a.repo, {"."}) != nil {
		return w, false
	}
	a.staged[FIRST] = "# fuzz\n"
	id, cerr := git.commit(a.repo, "first", SIG)
	if cerr != nil {
		return w, false
	}
	append(&a.history, id)
	a.committed[FIRST] = "# fuzz\n"
	if git.remote_add(a.repo, "origin", w.hub) != nil || git.push(a.repo, "origin") != nil {
		return w, false
	}
	w.branch, _, _ = git.head(a.repo)
	append(&w.hub_history, id)
	w.hub_files[FIRST] = "# fuzz\n"

	b := &w.clones[1]
	b.name, b.dir = "b", path.join(root, "b")
	brepo, clerr := git.clone(w.hub, b.dir)
	if clerr != nil {
		return w, false
	}
	b.repo = brepo
	append(&b.history, id)
	b.files[FIRST], b.staged[FIRST], b.committed[FIRST] = "# fuzz\n", "# fuzz\n", "# fuzz\n"
	return w, true
}

teardown :: proc(w: ^^World) {
	if w^ == nil {
		return
	}
	for &c in w^.clones {
		git.close(&c.repo)
	}
	if w^.root != "" {
		os.remove_all(w^.root)
	}
	w^ = nil
}

// ---------------------------------------------------------------- sequence

Op :: enum u8 {
	Write,
	Delete,
	Add,
	Commit,
	Push,
	Fetch,
	Pull,
}

// FILES are the paths a case writes to; two under a directory, so adds
// and deletes cross a directory boundary.
FILES := []string{"notes.md", "AI/MEMORY.md", "AI/LEARNINGS.md", "handoffs/today.md"}

// LINES are the pieces a file's content is built from: short, so two
// writes to one file often coincide and a "modified" that is not one is
// exercised, with no NUL, which strings_round_trip owns.
LINES := []string{"- **a** — one — 2026-09-28\n", "line\n", "é and 😀\n", "\n", "tab\there\n", "x", "\r\n", "  indented\n"}

// sequence drives one random sequence of operations over the two clones
// and holds every step against the model.
sequence :: proc(w: ^World, src: ^harness.Source) -> (detail: string, ok: bool) {
	steps := harness.integer_in(src, 1, 25)
	trace := strings.builder_make()
	for step in 0 ..< steps {
		c := &w.clones[harness.integer_in(src, 0, 2)]
		op := Op(harness.integer_in(src, 0, len(Op)))
		fmt.sbprintf(&trace, "%s %s; ", op, c.name)
		if detail, ok = apply(w, c, op, src); !ok {
			return fmt.tprintf("step %d, %s on %s: %s [%s]", step, op, c.name, detail, strings.to_string(trace)), false
		}
		if detail, ok = check_trees(c); !ok {
			return fmt.tprintf("step %d, after %s on %s: %s [%s]", step, op, c.name, detail, strings.to_string(trace)), false
		}
	}
	return "", true
}

// apply performs op on c for real and in the model, and checks what that
// one operation promises.
apply :: proc(w: ^World, c: ^Clone, op: Op, src: ^harness.Source) -> (detail: string, ok: bool) {
	switch op {
	case .Write:
		f := harness.choice(src, FILES)
		// The name goes into the content so no two files ever hold the
		// same bytes: status is asked for no rename detection, and the
		// model has no notion of one either.
		content := strings.concatenate({f, "\n", harness.text(src, LINES, 4)})
		if err := path.write(path.join(c.dir, f), content); err != nil {
			return fmt.tprintf("write %s: %v", f, err), false
		}
		c.files[f] = content
	case .Delete:
		f := harness.choice(src, FILES)
		if f in c.files {
			os.remove(path.join(c.dir, f))
			delete_key(&c.files, f)
		}
	case .Add:
		if err := git.add(c.repo, {"."}); err != nil {
			return fmt.tprintf("add: %v", err), false
		}
		copy_map(&c.staged, c.files)
	case .Commit:
		msg := fmt.tprintf("%s: step %d", c.name, len(c.history))
		id, err := git.commit(c.repo, msg, SIG)
		if err != nil {
			return fmt.tprintf("commit: %v", err), false
		}
		append(&c.history, id)
		copy_map(&c.committed, c.staged)
		got, lerr := git.log(c.repo, limit = 1)
		if lerr != nil || len(got) != 1 || got[0].id != id || got[0].summary != msg {
			return fmt.tprintf("log after commit: %v, %v", got, lerr), false
		}
		if patch, derr := git.diff(c.repo, staged = true); derr != nil || patch != "" {
			return fmt.tprintf("staged diff after commit is not empty: %v %q", derr, patch), false
		}
	case .Push:
		allowed := is_prefix(w.hub_history[:], c.history[:])
		err := git.push(c.repo, "origin")
		if allowed && err != nil {
			return fmt.tprintf("push refused though the hub is behind: %v", err), false
		}
		if !allowed {
			f, is_fault := err.(git.Fault)
			if !is_fault || f.code != git.GIT_ENONFASTFORWARD {
				return fmt.tprintf("push of a diverged clone was not refused as non-fast-forward: %v", err), false
			}
			return "", true
		}
		set_history(&w.hub_history, c.history[:])
		copy_map(&w.hub_files, c.committed)
		hub, herr := git.open(w.hub)
		if herr != nil {
			return fmt.tprintf("open hub: %v", herr), false
		}
		defer git.close(&hub)
		_, hid, born := git.head(hub)
		if !born || hid != c.history[len(c.history) - 1] {
			return fmt.tprintf("hub head %s after push of %s", hid, c.history[len(c.history) - 1]), false
		}
	case .Fetch:
		if err := git.fetch(c.repo, "origin"); err != nil {
			return fmt.tprintf("fetch: %v", err), false
		}
		common := common_prefix(c.history[:], w.hub_history[:])
		ahead, behind, aerr := git.ahead_behind(c.repo, "origin")
		if aerr != nil || ahead != len(c.history) - common || behind != len(w.hub_history) - common {
			return fmt.tprintf("ahead/behind %d/%d, model %d/%d: %v", ahead, behind, len(c.history) - common, len(w.hub_history) - common, aerr), false
		}
	case .Pull:
		_, before, _ := git.head(c.repo)
		dirty := !maps_equal(c.files, c.committed) || !maps_equal(c.staged, c.committed)
		// The hub behind or level with the clone is nothing to take; the
		// clone strictly behind is a fast-forward; anything else has
		// commits on both sides.
		want: git.Sync
		switch {
		case is_prefix(w.hub_history[:], c.history[:]):
			want = .Up_To_Date
		case is_prefix(c.history[:], w.hub_history[:]):
			want = .Fast_Forwarded
		case:
			want = .Diverged
		}
		sync, err := git.pull(c.repo, "origin")
		if want == .Fast_Forwarded && dirty {
			// A fast-forward would overwrite uncommitted work: the wrapper
			// must refuse rather than reset over it.
			f, is_fault := err.(git.Fault)
			if !is_fault || f.code != git.GIT_EUNCOMMITTED {
				return fmt.tprintf("pull onto a dirty tree was not refused: %v %v", sync, err), false
			}
			_, after, _ := git.head(c.repo)
			if after != before {
				return "a refused pull moved HEAD", false
			}
			return "", true
		}
		if err != nil {
			return fmt.tprintf("pull: %v", err), false
		}
		if sync != want {
			return fmt.tprintf("pull reported %v, model says %v", sync, want), false
		}
		switch sync {
		case .Fast_Forwarded:
			set_history(&c.history, w.hub_history[:])
			copy_map(&c.committed, w.hub_files)
			copy_map(&c.staged, w.hub_files)
			copy_map(&c.files, w.hub_files)
			_, after, _ := git.head(c.repo)
			if after != w.hub_history[len(w.hub_history) - 1] {
				return fmt.tprintf("fast-forwarded to %s, hub is at %s", after, w.hub_history[len(w.hub_history) - 1]), false
			}
			for f, content in w.hub_files {
				got, rerr := path.read(path.join(c.dir, f))
				if rerr != nil || got != content {
					return fmt.tprintf("after fast-forward %s reads %q, hub has %q", f, got, content), false
				}
			}
		case .Up_To_Date, .Diverged:
			_, after, _ := git.head(c.repo)
			if after != before {
				return fmt.tprintf("a %v pull moved HEAD", sync), false
			}
		}
	}
	return "", true
}

// check_trees asks status and log and holds them against the model's
// three trees and history.
check_trees :: proc(c: ^Clone) -> (detail: string, ok: bool) {
	entries, err := git.status(c.repo)
	if err != nil {
		return fmt.tprintf("status: %v", err), false
	}
	want := model_status(c)
	slice.sort_by(entries, proc(a, b: git.Entry) -> bool {return a.path < b.path})
	if len(entries) != len(want) {
		return fmt.tprintf("status has %d entries, model %d: %v vs %v", len(entries), len(want), entries, want), false
	}
	for e, i in entries {
		m := want[i]
		if e.path != m.path || e.index != m.index || e.worktree != m.worktree || e.conflicted {
			return fmt.tprintf("status %v, model %v", e, m), false
		}
	}
	commits, lerr := git.log(c.repo)
	if lerr != nil || len(commits) != len(c.history) {
		return fmt.tprintf("log has %d commits, model %d: %v", len(commits), len(c.history), lerr), false
	}
	for cm, i in commits {
		if cm.id != c.history[len(c.history) - 1 - i] {
			return fmt.tprintf("log[%d] is %s, model %s", i, cm.id, c.history[len(c.history) - 1 - i]), false
		}
	}
	return "", true
}

// model_status is what status must say: one entry per path whose three
// trees disagree, sorted by path.
model_status :: proc(c: ^Clone) -> []git.Entry {
	paths := make(map[string]bool)
	for p in c.files {paths[p] = true}
	for p in c.staged {paths[p] = true}
	for p in c.committed {paths[p] = true}
	out := make([dynamic]git.Entry)
	for p in paths {
		e := git.Entry {
			path     = p,
			index    = change_between(c.committed, c.staged, p),
			worktree = change_between(c.staged, c.files, p),
		}
		if e.index != .None || e.worktree != .None {
			append(&out, e)
		}
	}
	slice.sort_by(out[:], proc(a, b: git.Entry) -> bool {return a.path < b.path})
	return out[:]
}

change_between :: proc(from, to: map[string]string, p: string) -> git.Change {
	a, in_from := from[p]
	b, in_to := to[p]
	switch {
	case in_from && !in_to:
		return .Deleted
	case !in_from && in_to:
		return .New
	case in_from && in_to && a != b:
		return .Modified
	}
	return .None
}

copy_map :: proc(dst: ^map[string]string, src: map[string]string) {
	clear(dst)
	for k, v in src {
		dst[k] = v
	}
}

maps_equal :: proc(a, b: map[string]string) -> bool {
	if len(a) != len(b) {
		return false
	}
	for k, v in a {
		if w, in_b := b[k]; !in_b || w != v {
			return false
		}
	}
	return true
}

set_history :: proc(dst: ^[dynamic]string, src: []string) {
	clear(dst)
	append(dst, ..src)
}

is_prefix :: proc(prefix, of: []string) -> bool {
	return len(prefix) <= len(of) && slice.equal(prefix, of[:len(prefix)])
}

common_prefix :: proc(a, b: []string) -> int {
	n := 0
	for n < len(a) && n < len(b) && a[n] == b[n] {
		n += 1
	}
	return n
}

// ---------------------------------------------------------------- strings

// NAME_PIECES build paths and remote names out of what a filesystem or a
// refspec might choke on, NUL and invalid UTF-8 among them.
NAME_PIECES := []string{"a", "b", "notes", ".md", "/", ".", "..", "-", " ", "é", "😀", "\xff\xfe", "\x00", ":", "*", "~", "^", "\\", "\n"}

// strings_round_trip commits a generated message, adds a generated path
// and configures a generated remote, and reads each back. The promise is
// the same for all three: it comes back byte for byte, or the call said
// no. A NUL in an Odin string is where a C boundary would silently cut.
strings_round_trip :: proc(w: ^World, src: ^harness.Source) -> (detail: string, ok: bool) {
	a := &w.clones[0]

	msg := harness.text(src, harness.AWKWARD, 12)
	if msg == "" {
		msg = "m"
	}
	id, cerr := git.commit(a.repo, msg, SIG)
	if cerr != nil {
		if !strings.contains(msg, "\x00") {
			return fmt.tprintf("commit refused a message without a NUL: %s: %v", harness.show(msg), cerr), false
		}
	} else {
		got, lerr := git.log(a.repo, limit = 1)
		if lerr != nil || len(got) != 1 || got[0].id != id {
			return fmt.tprintf("log after commit: %v", lerr), false
		}
		if got[0].message != msg {
			return fmt.tprintf("message %s came back as %s", harness.show(msg), harness.show(got[0].message)), false
		}
	}

	rel := harness.text(src, NAME_PIECES, 6)
	if writable(a.dir, rel) {
		if err := path.write(path.join(a.dir, rel), "x"); err == nil {
			if aerr := git.add(a.repo, {"."}); aerr != nil {
				if !strings.contains(rel, "\x00") {
					return fmt.tprintf("add refused after writing %s: %v", harness.show(rel), aerr), false
				}
			} else {
				entries, serr := git.status(a.repo)
				if serr != nil {
					return fmt.tprintf("status after adding %s: %v", harness.show(rel), serr), false
				}
				for e in entries {
					if e.worktree != .None {
						return fmt.tprintf("after add of %s, %s is still unstaged", harness.show(rel), harness.show(e.path)), false
					}
				}
			}
		}
	}

	name := harness.text(src, NAME_PIECES, 4)
	if name == "" {
		name = "r"
	}
	if err := git.remote_add(a.repo, name, w.hub); err == nil {
		rs, rerr := git.remotes(a.repo)
		if rerr != nil {
			return fmt.tprintf("remotes after adding %s: %v", harness.show(name), rerr), false
		}
		found := false
		for r in rs {
			if r.name == name && r.url == w.hub {
				found = true
			}
		}
		if !found {
			return fmt.tprintf("remote %s was accepted but is not listed as itself: %v", harness.show(name), rs), false
		}
	} else if _, is_fault := err.(git.Fault); !is_fault {
		return fmt.tprintf("remote_add %s failed with something other than a Fault", harness.show(name)), false
	}
	return "", true
}

// writable says whether rel is a path this suite may create under dir:
// inside it, once cleaned, and not inside .git, whose files are the
// repository itself.
writable :: proc(dir, rel: string) -> bool {
	if rel == "" || strings.contains(rel, "\x00") {
		return false
	}
	full := path.join(dir, rel)
	prefix := strings.concatenate({dir, "/"})
	if !strings.has_prefix(full, prefix) || len(full) == len(prefix) {
		return false
	}
	inside := full[len(prefix):]
	return inside != ".git" && !strings.has_prefix(inside, ".git/") && !strings.has_suffix(inside, "/")
}

// ---------------------------------------------------------------- damaged

// TARGETS are the files under .git a corruption is most likely to reach:
// the pointer to the branch, the index, the config, and the branch itself.
// Loose objects are not among them. Corrupting one hung this suite against
// libgit2 1.9.7, the system library and the static build alike, on a
// truncated object and on random bytes over one; a gdb backtrace put the
// spin in git_zstream_get_output under read_loose, whose loop in
// src/util/zstream.c runs while inflate reports Z_BUF_ERROR on exhausted
// input and zstream_seterr does not count that as an error. The suite has
// no cancel to cut such a case short, so the object store stays out until
// upstream returns from it.
TARGETS := []string{"HEAD", "index", "config", "refs/heads/%s"}

// damaged corrupts one file of clone a's repository and asks the binding
// about the repository. Every answer is a value or a Fault; the property
// is that the process is still here to hear it.
damaged :: proc(w: ^World, src: ^harness.Source) -> (detail: string, ok: bool) {
	a := &w.clones[0]
	target := harness.choice(src, TARGETS)
	if target == "refs/heads/%s" {
		target = fmt.tprintf(target, w.branch)
	}
	file := path.join(a.dir, ".git", target)
	body, rerr := path.read(file)
	if rerr != nil {
		return fmt.tprintf("%s is missing before damage: %v", target, rerr), false
	}
	broken, _ := harness.damage(src, {transmute([]byte)body})
	if err := path.write(file, string(broken)); err != nil {
		return fmt.tprintf("rewrite %s: %v", target, err), false
	}
	repo, oerr := git.open(a.dir)
	if oerr != nil {
		return "", true // a refusal to open is a fine answer
	}
	defer git.close(&repo)
	git.head(repo)
	git.log(repo)
	git.status(repo)
	git.diff(repo, staged = true)
	git.diff(repo, staged = false)
	git.ahead_behind(repo, "origin")
	return "", true
}
