package main

import "core:fmt"
import "core:hash"
import "core:strings"
import "core:unicode/utf8"

// File is one generated file, named relative to the package directory.
File :: struct {
	name: string,
	text: string,
}

CODE_FILE :: "queries_gen.odin"
TEST_FILE :: "queries_gen_test.odin"

GENERATED_HEADER :: "// Code generated by jm-sqlgen from schema.sql and queries.sql. DO NOT EDIT.\n"

// ada_case turns todo_state into Todo_State, the case jm gives types.
ada_case :: proc(name: string) -> string {
	sb: strings.Builder
	upper := true
	for r in name {
		if r == '_' {
			strings.write_rune(&sb, r)
			upper = true
			continue
		}
		strings.write_rune(&sb, upper && r >= 'a' && r <= 'z' ? r - 32 : r)
		upper = false
	}
	return strings.to_string(sb)
}

sql_const :: proc(q: Query) -> string {
	return fmt.aprintf("%s_SQL", strings.to_upper(q.name))
}

// write_string_literal writes s as an Odin string literal: a raw one when it
// can be, so SQL reads as written, and an escaped one otherwise.
write_string_literal :: proc(sb: ^strings.Builder, s: string) {
	valid := utf8.valid_string(s)
	raw := valid && !strings.contains_rune(s, '`')
	for b in transmute([]byte)s {
		if b < 0x20 && b != '\n' && b != '\t' {
			raw = false
		}
	}
	if raw {
		fmt.sbprintf(sb, "`%s`", s)
		return
	}
	strings.write_byte(sb, '"')
	for b in transmute([]byte)s {
		switch b {
		case '"':
			strings.write_string(sb, `\"`)
		case '\\':
			strings.write_string(sb, `\\`)
		case '\n':
			strings.write_string(sb, `\n`)
		case '\t':
			strings.write_string(sb, `\t`)
		case:
			if b < 0x20 || (b >= 0x80 && !valid) {
				fmt.sbprintf(sb, `\x%02x`, b)
			} else {
				strings.write_byte(sb, b)
			}
		}
	}
	strings.write_byte(sb, '"')
}

write_doc :: proc(sb: ^strings.Builder, lines: []string, indent := "") {
	for line in lines {
		if line == "" {
			fmt.sbprintf(sb, "%s//\n", indent)
		} else {
			fmt.sbprintf(sb, "%s// %s\n", indent, line)
		}
	}
}

// write_hash_guard asserts at compile time that file still hashes as it did
// when the code was generated, so editing it without regenerating fails the
// build instead of leaving the code behind the SQL.
write_hash_guard :: proc(sb: ^strings.Builder, file, text: string) {
	fmt.sbprintf(
		sb,
		"#assert(\n\t#hash(#load(%q, string), \"fnv64a\") == 0x%016x,\n" +
		"\t\"%s changed: run jm-sqlgen\",\n)\n",
		file,
		hash.fnv64a(transmute([]byte)text),
		file,
	)
}

// write_comment writes text as // lines, broken at spaces to keep each line
// within jm's 100 columns. A word longer than that stays whole.
write_comment :: proc(sb: ^strings.Builder, text: string) {
	WIDTH :: 100 - len("// ")
	line := 0
	rest := text
	for word in strings.fields_iterator(&rest) {
		if line > 0 && line + 1 + len(word) > WIDTH {
			strings.write_byte(sb, '\n')
			line = 0
		}
		if line == 0 {
			strings.write_string(sb, "//")
		}
		strings.write_byte(sb, ' ')
		strings.write_string(sb, word)
		line += 1 + len(word)
	}
	if line > 0 {
		strings.write_byte(sb, '\n')
	}
}
