// Code generated by jm-sqlgen from schema.sql and queries.sql. DO NOT EDIT.

package todo_db

import "core:testing"

import "jm:sqlite3"

@(private = "file")
Sqlgen_Set :: struct {
	name:   string,
	seed:   string,
	int_v:  i64,
	real_v: f64,
	text_v: string,
	blob_v: string,
	bool_v: bool,
	nulls:  bool,
}

// SQLGEN_SETS are the database states every query runs against: nothing at
// all, which empties aggregates and subqueries; every nullable column NULL;
// the extremes of each type; and each table alone, which leaves the other
// side of an outer join missing.
// low: todo.done holds the base value, since todo refused the set's own: CHECK constraint failed:
// done IN (0, 1).
// high: todo.done holds the base value, since todo refused the set's own: CHECK constraint failed:
// done IN (0, 1).
@(private = "file")
SQLGEN_SETS := [?]Sqlgen_Set {
	{
		name = "empty",
		seed = ``,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = false,
	},
	{
		name = "nulls",
		seed = `INSERT INTO "todo"("id", "title", "done")
VALUES (1, 'a', 1);
`,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = true,
	},
	{
		name = "low",
		seed = `INSERT INTO "todo"("id", "title", "done")
VALUES (-9223372036854775808, '', 1);
`,
		int_v = -9223372036854775808,
		real_v = -1.5,
		text_v = ``,
		blob_v = ``,
		bool_v = false,
		nulls = false,
	},
	{
		name = "high",
		seed = `INSERT INTO "todo"("id", "title", "done")
VALUES (9223372036854775807, 'zß€😀', 1);
`,
		int_v = 9223372036854775807,
		real_v = 1e+300,
		text_v = `zß€😀`,
		blob_v = "\x00\xff",
		bool_v = true,
		nulls = false,
	},
}

// Each query runs in every data set through its generated proc, which
// checks every value it reads against the type it was generated with. check
// runs too, against the schema as SQLite holds it.
@(test)
sqlgen_queries_hold_their_types :: proc(t: ^testing.T) {
	context.allocator = context.temp_allocator
	for set in SQLGEN_SETS {
		db, err := sqlite3.open(sqlite3.MEMORY)
		if !testing.expectf(t, err == nil, "data set %s: open: %v", set.name, err) {
			return
		}
		defer sqlite3.close(&db)
		testing.expect_value(t, sqlite3.exec(db, #load("schema.sql", string)), nil)
		testing.expect_value(t, sqlite3.exec(db, set.seed), nil)
		testing.expect_value(t, check(db), nil)
		sqlgen_run(t, db, set)
	}
}

@(private = "file")
sqlgen_run :: proc(t: ^testing.T, db: sqlite3.Db, set: Sqlgen_Set) {
	{
		sqlgen_begin(t, db)
		_, _, err := todo_state(db, sqlgen_int(set, i64))
		sqlgen_end(t, db, set, "todo_state", err)
	}
	{
		sqlgen_begin(t, db)
		_, _, err := counts(db)
		sqlgen_end(t, db, set, "counts", err)
	}
	{
		sqlgen_begin(t, db)
		rows, err := todos_open(db, sqlgen_int(set, i64))
		if err == nil {
			for _ in todos_next(&rows) {
			}
			err = todos_close(&rows)
		}
		sqlgen_end(t, db, set, "todos_open", err)
	}
	{
		sqlgen_begin(t, db)
		rows: Todos_Rows
		if todos(&rows, db, sqlgen_int(set, i64)) {
			for _ in todos_next(&rows) {
			}
		}
		sqlgen_end(t, db, set, "todos", rows.err)
	}
	{
		sqlgen_begin(t, db)
		_, err := todos_all(db, sqlgen_int(set, i64))
		sqlgen_end(t, db, set, "todos_all", err)
	}
	{
		sqlgen_begin(t, db)
		err := insert(db, set.text_v)
		sqlgen_end(t, db, set, "insert", err)
	}
	{
		sqlgen_begin(t, db)
		err := set_done(db, sqlgen_int(set, i64), set.bool_v)
		sqlgen_end(t, db, set, "set_done", err)
	}
	{
		sqlgen_begin(t, db)
		err := set_all(db, set.bool_v)
		sqlgen_end(t, db, set, "set_all", err)
	}
	{
		sqlgen_begin(t, db)
		err := set_title(db, sqlgen_int(set, i64), set.text_v)
		sqlgen_end(t, db, set, "set_title", err)
	}
	{
		sqlgen_begin(t, db)
		err := remove(db, sqlgen_int(set, i64))
		sqlgen_end(t, db, set, "remove", err)
	}
	{
		sqlgen_begin(t, db)
		err := remove_done(db)
		sqlgen_end(t, db, set, "remove_done", err)
	}
}

@(private = "file")
sqlgen_maybe :: proc(v: $T, null: bool) -> Maybe(T) {
	if null {
		return nil
	}
	return v
}

// sqlgen_int is the set's integer as T, held to T's range, so the extremes
// of the set are the extremes of each width.
@(private = "file")
sqlgen_int :: proc(set: Sqlgen_Set, $T: typeid) -> T {
	return T(clamp(set.int_v, i64(min(T)), i64(max(T))))
}

// sqlgen_real is the set's float as T, held to T's finite range.
@(private = "file")
sqlgen_real :: proc(set: Sqlgen_Set, $T: typeid) -> T {
	return T(clamp(set.real_v, -f64(max(T)), f64(max(T))))
}

@(private = "file")
sqlgen_begin :: proc(t: ^testing.T, db: sqlite3.Db) {
	testing.expect_value(t, sqlite3.exec(db, "SAVEPOINT sqlgen"), nil)
}

// sqlgen_end undoes what the query changed, and fails the test unless the
// query succeeded or a constraint the data set happens to break refused it.
// A STRICT column refusing a parameter's type is not such a constraint.
@(private = "file")
sqlgen_end :: proc(
	t: ^testing.T,
	db: sqlite3.Db,
	set: Sqlgen_Set,
	query: string,
	err: sqlite3.Error,
) {
	testing.expect_value(t, sqlite3.exec(db, "ROLLBACK TO sqlgen; RELEASE sqlgen"), nil)
	f, failed := err.(sqlite3.Fault)
	if !failed {
		return
	}
	broke_a_constraint := f.code == .Constraint && f.extended != sqlite3.CONSTRAINT_DATATYPE
	testing.expectf(t, broke_a_constraint, "data set %s: %s: %v: %s", set.name, query, f.code, f.text)
}
