// Code generated by jm-sqlgen from schema.sql and queries.sql. DO NOT EDIT.

package todo_db

import "core:fmt"

import "jm:sqlite3"

// Editing either file without regenerating fails the build here.
#assert(
	#hash(#load("schema.sql", string), "fnv64a") == 0x32ead840064f78fd,
	"schema.sql changed: run jm-sqlgen",
)
#assert(
	#hash(#load("queries.sql", string), "fnv64a") == 0x29141375c147e9ac,
	"queries.sql changed: run jm-sqlgen",
)

@(private = "file")
TODO_STATE_SQL :: `SELECT done AS "done: bool" FROM todo WHERE id = @id`

// Todo_State_Row is a row of todo_state. Text and blob fields are allocated in the
// allocator the query was given.
Todo_State_Row :: struct {
	done: bool, // annotated, not inferred
}

// Whether todo id is done; no row when it does not exist.
//
// todo_state is :one in queries.sql.
todo_state :: proc(
	db: sqlite3.Db,
	id: i64,
	allocator := context.allocator,
) -> (
	row: Todo_State_Row,
	found: bool,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		TODO_STATE_SQL,
		id,
		allocator = allocator,
	) or_return
	if sqlite3.next(&stmt) {
		found = true
		row.done = sqlite3.read_exact(&stmt, 0, bool)
		if stmt.err == nil && sqlite3.next(&stmt) {
			stmt.err = sqlite3.Fault {
				code = .Misuse,
				text = fmt.aprint("todo_state is :one but returned a second row", allocator = allocator),
			}
		}
	}
	if err = sqlite3.finish(&stmt); err != nil {
		return {}, false, err
	}
	return
}

@(private = "file")
COUNTS_SQL :: `SELECT
	COUNT(*) FILTER (WHERE done = 0) AS "active: i64",
	COUNT(*) FILTER (WHERE done = 1) AS "completed: i64"
FROM todo`

// Counts_Row is a row of counts. Text and blob fields are allocated in the
// allocator the query was given.
Counts_Row :: struct {
	active:    i64, // annotated, not inferred
	completed: i64, // annotated, not inferred
}

// How many todos are active and how many done.
//
// counts is :one in queries.sql.
counts :: proc(
	db: sqlite3.Db,
	allocator := context.allocator,
) -> (
	row: Counts_Row,
	found: bool,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		COUNTS_SQL,
		allocator = allocator,
	) or_return
	if sqlite3.next(&stmt) {
		found = true
		row.active = sqlite3.read_exact(&stmt, 0, i64)
		row.completed = sqlite3.read_exact(&stmt, 1, i64)
		if stmt.err == nil && sqlite3.next(&stmt) {
			stmt.err = sqlite3.Fault {
				code = .Misuse,
				text = fmt.aprint("counts is :one but returned a second row", allocator = allocator),
			}
		}
	}
	if err = sqlite3.finish(&stmt); err != nil {
		return {}, false, err
	}
	return
}

@(private = "file")
TODOS_SQL :: `SELECT id, title, done AS "done: bool"
FROM todo
WHERE @filter = 0 OR (@filter = 1 AND done = 0) OR (@filter = 2 AND done = 1)
ORDER BY id`

// Todos_Row is a row of todos. Text and blob fields are allocated in the
// allocator the query was given.
Todos_Row :: struct {
	id:    i64,
	title: string,
	done:  bool, // annotated, not inferred
}

// Todos_Rows is a cursor over the rows of todos. err is what stopped it, once it
// is closed: a failed start, a failed step, or a value of the wrong type.
Todos_Rows :: struct {
	stmt: sqlite3.Stmt,
	err:  sqlite3.Error,
}

// The todos a filter keeps, by query.Filter's value: 0 all, 1 active,
// 2 completed.
//
// todos is :many in queries.sql: todos_open as a guard. Written
// `if todos(&rows, db, ...) { for row in todos_next(&rows) { ... } }`, it closes
// the cursor at the end of the if and leaves what stopped it in rows.err,
// which a deferred close cannot return. It is false if the query cannot start.
@(deferred_in = todos_guard_close)
todos :: proc(
	rows: ^Todos_Rows,
	db: sqlite3.Db,
	filter: i64,
	allocator := context.allocator,
) -> bool {
	opened, err := todos_open(db, filter, allocator)
	rows^ = opened
	rows.err = err
	return err == nil
}

@(private = "file")
todos_guard_close :: proc(
	rows: ^Todos_Rows,
	db: sqlite3.Db,
	filter: i64,
	allocator := context.allocator,
) {
	todos_close(rows)
}

// todos_open starts todos: step the cursor with todos_next and end it with
// todos_close. Text and blobs are allocated in allocator.
todos_open :: proc(
	db: sqlite3.Db,
	filter: i64,
	allocator := context.allocator,
) -> (
	rows: Todos_Rows,
	err: sqlite3.Error,
) {
	rows.stmt = sqlite3.query(
		db,
		TODOS_SQL,
		filter,
		allocator = allocator,
	) or_return
	return
}

// todos_next reads the next row; ok is false at the end or on a failure.
todos_next :: proc(rows: ^Todos_Rows) -> (row: Todos_Row, ok: bool) {
	if !sqlite3.next(&rows.stmt) {
		return
	}
	row.id = sqlite3.read_exact(&rows.stmt, 0, i64)
	row.title = sqlite3.read_exact(&rows.stmt, 1, string)
	row.done = sqlite3.read_exact(&rows.stmt, 2, bool)
	if rows.stmt.err != nil {
		todos_free_row(row, rows.stmt.allocator)
		return {}, false
	}
	return row, true
}

// todos_close ends the cursor and returns what stopped it, which it also
// keeps in rows.err. Closing twice is safe.
todos_close :: proc(rows: ^Todos_Rows) -> sqlite3.Error {
	if err := sqlite3.finish(&rows.stmt); rows.err == nil {
		rows.err = err
	}
	return rows.err
}

// todos_all reads every row of todos into a slice in allocator, with their
// text and blobs; free it with todos_free. On a failure it frees what it read.
todos_all :: proc(
	db: sqlite3.Db,
	filter: i64,
	allocator := context.allocator,
) -> (
	all: []Todos_Row,
	err: sqlite3.Error,
) {
	rows := todos_open(db, filter, allocator) or_return
	out := make([dynamic]Todos_Row, allocator)
	for row in todos_next(&rows) {
		append(&out, row)
	}
	if err = todos_close(&rows); err != nil {
		todos_free(out[:], allocator)
		return nil, err
	}
	return out[:], nil
}

// todos_free_row frees the text and blobs of row, which are in allocator.
todos_free_row :: proc(row: Todos_Row, allocator := context.allocator) {
	delete(row.title, allocator)
}

// todos_free frees all, as todos_all returns it, with every row's text and
// blobs.
todos_free :: proc(all: []Todos_Row, allocator := context.allocator) {
	for row in all {
		todos_free_row(row, allocator)
	}
	delete(all, allocator)
}

@(private = "file")
INSERT_SQL :: `INSERT INTO todo(title) VALUES (@title)`

// insert is :exec in queries.sql.
insert :: proc(
	db: sqlite3.Db,
	title: string,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		INSERT_SQL,
		title,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

@(private = "file")
SET_DONE_SQL :: `UPDATE todo SET done = @done WHERE id = @id`

// set_done is :exec in queries.sql.
set_done :: proc(
	db: sqlite3.Db,
	id: i64,
	done: bool,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		SET_DONE_SQL,
		done,
		id,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

@(private = "file")
SET_ALL_SQL :: `UPDATE todo SET done = @done WHERE done != @done`

// Touches only the rows that differ, so the change batch names only those.
//
// set_all is :exec in queries.sql.
set_all :: proc(
	db: sqlite3.Db,
	done: bool,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		SET_ALL_SQL,
		done,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

@(private = "file")
SET_TITLE_SQL :: `UPDATE todo SET title = @title WHERE id = @id`

// set_title is :exec in queries.sql.
set_title :: proc(
	db: sqlite3.Db,
	id: i64,
	title: string,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		SET_TITLE_SQL,
		title,
		id,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

@(private = "file")
REMOVE_SQL :: `DELETE FROM todo WHERE id = @id`

// remove is :exec in queries.sql.
remove :: proc(
	db: sqlite3.Db,
	id: i64,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		REMOVE_SQL,
		id,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

@(private = "file")
REMOVE_DONE_SQL :: `DELETE FROM todo WHERE done = 1`

// remove_done is :exec in queries.sql.
remove_done :: proc(
	db: sqlite3.Db,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		REMOVE_DONE_SQL,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

// check prepares every query against db and compares the parameters and
// columns each has there with those it was generated for, so a database
// whose schema has drifted from schema.sql fails when it is opened rather
// than when a query first runs.
check :: proc(db: sqlite3.Db, allocator := context.allocator) -> sqlite3.Error {
	sqlite3.check_statement(
		db,
		"todo_state",
		TODO_STATE_SQL,
		1,
		{"done: bool"},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"counts",
		COUNTS_SQL,
		0,
		{"active: i64", "completed: i64"},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"todos",
		TODOS_SQL,
		1,
		{"id", "title", "done: bool"},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"insert",
		INSERT_SQL,
		1,
		{},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"set_done",
		SET_DONE_SQL,
		2,
		{},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"set_all",
		SET_ALL_SQL,
		1,
		{},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"set_title",
		SET_TITLE_SQL,
		2,
		{},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"remove",
		REMOVE_SQL,
		1,
		{},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"remove_done",
		REMOVE_DONE_SQL,
		0,
		{},
		allocator,
	) or_return
	return nil
}
