package pq

import "core:fmt"
import "core:math"
import "core:strconv"
import "core:strings"
import "core:unicode/utf8"

// Value is one typed parameter for exec_values. nil is NULL. Each is sent as
// the text PostgreSQL reads for its type: a bool as t or f, a []byte in
// bytea's hex form, a float in the shortest form that reads back the same.
Value :: union {
	bool,
	i16,
	i32,
	i64,
	f32,
	f64,
	string,
	[]byte,
}

// exec_values runs one statement with args filling $1, $2 and so on. It is
// exec for typed values, and the only way to pass a NULL: code generated by
// tools/jm-sqlgen binds through it.
exec_values :: proc(
	conn: ^Conn,
	sql: string,
	args: []Value,
	allocator := context.allocator,
) -> (
	result: Result,
	err: Error,
) {
	if conn == nil || conn.raw == nil {
		return {}, refusal("the connection is closed", 0, allocator)
	}
	if i := strings.index_byte(sql, 0); i >= 0 {
		return {}, refusal(fmt.tprintf("statement holds a NUL byte at offset %d, which libpq would read as its end", i), utf8.rune_count_in_string(sql[:i]) + 1, allocator)
	}
	values := make([]cstring, len(args), context.temp_allocator)
	for arg, n in args {
		text, null := value_text(arg)
		if null {
			continue
		}
		if i := strings.index_byte(text, 0); i >= 0 {
			return {}, refusal(fmt.tprintf("argument %d holds a NUL byte at offset %d, which libpq would read as its end", n + 1, i), 0, allocator)
		}
		values[n] = strings.clone_to_cstring(text, context.temp_allocator)
	}
	text := strings.clone_to_cstring(sql, context.temp_allocator)
	return read_result(conn, exec_params(conn, text, values), allocator)
}

// nullable is v as a parameter: its value, or NULL when it has none.
nullable :: proc(v: Maybe($T)) -> Value {
	if x, ok := v.?; ok {
		return x
	}
	return nil
}

// read_exact reads cell, a value of the column named column, as T: bool,
// i16, i32, i64, f32, f64, string or []byte. A value that is NULL, does not
// parse as T, or does not fit it sets err, unless err is already set, and
// reads as T's zero; so a caller reads a whole row and then checks err once.
// Text and blobs are copied into allocator. Code generated by tools/jm-sqlgen
// reads every column this way.
read_exact :: proc(
	cell: Maybe(string),
	column: string,
	$T: typeid,
	err: ^Error,
	allocator := context.allocator,
) -> (
	v: T,
) where T == bool ||
	T == i16 ||
	T == i32 ||
	T == i64 ||
	T == f32 ||
	T == f64 ||
	T == string ||
	T == []byte {
	text, present := cell.?
	if !present {
		misread(err, column, "NULL", T, allocator)
		return
	}
	ok := false
	when T == bool {
		v, ok = text == "t", text == "t" || text == "f"
	} else when T == i16 || T == i32 || T == i64 {
		n, parsed := strconv.parse_i64(text)
		ok = parsed && n >= i64(min(T)) && n <= i64(max(T))
		v = T(n)
	} else when T == f32 || T == f64 {
		f: f64
		f, ok = parse_float(text)
		v = T(f)
	} else when T == string {
		v, ok = strings.clone(text, allocator), true
	} else {
		v, ok = decode_bytea(text, allocator)
	}
	if !ok {
		misread(err, column, text, T, allocator)
	}
	return
}

// read_exact_maybe reads cell as read_exact does, and as nil when it is NULL.
read_exact_maybe :: proc(
	cell: Maybe(string),
	column: string,
	$T: typeid,
	err: ^Error,
	allocator := context.allocator,
) -> (
	v: Maybe(T),
) {
	if _, present := cell.?; present {
		v = read_exact(cell, column, T, err, allocator)
	}
	return
}

// check_statement describes sql and compares it with the shape the calling
// code was written for: params parameters, and columns named columns in
// that order. It is how generated code finds that a database's schema has
// drifted before a query runs. A difference is a Fault naming name, with
// SQLSTATE 0A000.
check_statement :: proc(
	conn: ^Conn,
	name, sql: string,
	params: int,
	columns: []string,
	allocator := context.allocator,
) -> Error {
	desc, err := describe(conn, sql, context.temp_allocator)
	if f, failed := err.(Fault); failed {
		f.message = fmt.aprintf("%s: %s", name, f.message, allocator = allocator)
		return f
	}
	drift := ""
	switch {
	case len(desc.params) != params:
		drift = fmt.aprintf(
			"%s takes %d parameters, not %d",
			name,
			len(desc.params),
			params,
			allocator = allocator,
		)
	case len(desc.columns) != len(columns):
		drift = fmt.aprintf(
			"%s returns %d columns, not %d",
			name,
			len(desc.columns),
			len(columns),
			allocator = allocator,
		)
	case:
		for want, i in columns {
			if got := desc.columns[i].name; got != want {
				drift = fmt.aprintf(
					"%s names column %d %q, not %q",
					name,
					i + 1,
					got,
					want,
					allocator = allocator,
				)
				break
			}
		}
	}
	if drift == "" {
		return nil
	}
	return Fault{message = drift, sqlstate = strings.clone(FEATURE_NOT_SUPPORTED, allocator)}
}

// value_text is v as PostgreSQL's text input for its type, in the temp
// allocator; null is true for nil.
@(private = "file")
value_text :: proc(v: Value) -> (text: string, null: bool) {
	switch x in v {
	case bool:
		return x ? "t" : "f", false
	case i16:
		return fmt.tprint(x), false
	case i32:
		return fmt.tprint(x), false
	case i64:
		return fmt.tprint(x), false
	case f32:
		return float_text(f64(x), 32), false
	case f64:
		return float_text(x, 64), false
	case string:
		return x, false
	case []byte:
		sb := strings.builder_make(context.temp_allocator)
		strings.write_string(&sb, `\x`)
		for b in x {
			fmt.sbprintf(&sb, "%02x", b)
		}
		return strings.to_string(sb), false
	}
	return "", true
}

// float_text writes f in the shortest form that reads back as the same
// value, and the infinities and NaN as PostgreSQL spells them.
@(private = "file")
float_text :: proc(f: f64, bits: int) -> string {
	switch {
	case math.is_nan(f):
		return "NaN"
	case math.is_inf(f, 1):
		return "Infinity"
	case math.is_inf(f, -1):
		return "-Infinity"
	}
	buf := make([]byte, 32, context.temp_allocator)
	return strconv.write_float(buf, f, 'g', -1, bits)
}

@(private = "file")
parse_float :: proc(text: string) -> (f: f64, ok: bool) {
	switch text {
	case "NaN":
		return math.nan_f64(), true
	case "Infinity":
		return math.inf_f64(1), true
	case "-Infinity":
		return math.inf_f64(-1), true
	}
	return strconv.parse_f64(text)
}

// decode_bytea reads bytea's hex output form, \x followed by two hex digits
// a byte, which is PostgreSQL's default bytea_output; values_round_trip in the
// tests reads one back. A session set to the older escape form reads as a
// value that is not a []byte, an error rather than wrong bytes.
@(private = "file")
decode_bytea :: proc(text: string, allocator := context.allocator) -> (b: []byte, ok: bool) {
	if !strings.has_prefix(text, `\x`) || len(text) % 2 != 0 {
		return nil, false
	}
	hex := text[2:]
	b = make([]byte, len(hex) / 2, allocator)
	for i in 0 ..< len(b) {
		n, parsed := strconv.parse_u64_of_base(hex[2 * i:][:2], 16)
		if !parsed {
			delete(b, allocator)
			return nil, false
		}
		b[i] = byte(n)
	}
	return b, true
}

// misread sets err to a value that would not read as T, unless it is set.
@(private = "file")
misread :: proc(err: ^Error, column, text: string, $T: typeid, allocator := context.allocator) {
	if err^ != nil {
		return
	}
	err^ = Fault {
		message = fmt.aprintf(
			"column %s holds %q, which is not a %v",
			column,
			text,
			typeid_of(T),
			allocator = allocator,
		),
	}
}
