// Code generated by jm-sqlgen from schema.sql and queries.sql. DO NOT EDIT.

package i18n_db

import "core:fmt"

import "jm:sqlite3"

// Editing either file without regenerating fails the build here.
#assert(
	#hash(#load("schema.sql", string), "fnv64a") == 0xe898d3aafb676541,
	"schema.sql changed: run jm-sqlgen",
)
#assert(
	#hash(#load("queries.sql", string), "fnv64a") == 0x934a53719b11bbe5,
	"queries.sql changed: run jm-sqlgen",
)

@(private = "file")
SETTING_SQL :: `SELECT value FROM setting WHERE name = @name`

// Setting_Row is a row of setting. Text and blob fields are allocated in the
// allocator the query was given.
Setting_Row :: struct {
	value: string,
}

// The value saved under name; no row when none is.
//
// setting is :one in queries.sql.
setting :: proc(
	db: sqlite3.Db,
	name: string,
	allocator := context.allocator,
) -> (
	row: Setting_Row,
	found: bool,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		SETTING_SQL,
		name,
		allocator = allocator,
	) or_return
	if sqlite3.next(&stmt) {
		found = true
		row.value = sqlite3.read_exact(&stmt, 0, string)
		if stmt.err == nil && sqlite3.next(&stmt) {
			stmt.err = sqlite3.Fault {
				code = .Misuse,
				text = fmt.aprint("setting is :one but returned a second row", allocator = allocator),
			}
		}
	}
	if err = sqlite3.finish(&stmt); err != nil {
		setting_free_row(row, allocator)
		return {}, false, err
	}
	return
}

// setting_free_row frees the text and blobs of row, which are in allocator.
setting_free_row :: proc(row: Setting_Row, allocator := context.allocator) {
	delete(row.value, allocator)
}

@(private = "file")
SET_SETTING_SQL :: `INSERT INTO setting(name, value) VALUES (@name, @value)
ON CONFLICT(name) DO UPDATE SET value = excluded.value`

// Saves value under name, replacing what was there.
//
// set_setting is :exec in queries.sql.
set_setting :: proc(
	db: sqlite3.Db,
	name: string,
	value: string,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		SET_SETTING_SQL,
		name,
		value,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

// check prepares every query against db and compares the parameters and
// columns each has there with those it was generated for, so a database
// whose schema has drifted from schema.sql fails when it is opened rather
// than when a query first runs.
check :: proc(db: sqlite3.Db, allocator := context.allocator) -> sqlite3.Error {
	sqlite3.check_statement(
		db,
		"setting",
		SETTING_SQL,
		1,
		{"value"},
		allocator,
	) or_return
	sqlite3.check_statement(
		db,
		"set_setting",
		SET_SETTING_SQL,
		2,
		{},
		allocator,
	) or_return
	return nil
}
