// material-tokens writes jm:ui/material/tokens from the m3e-kit's resolved
// token file: every sys.* and comp.* token as a typed Odin constant, and
// the colour roles' light and dark values.
//
//	material-tokens <m3e-kit>/tokens/m3e.resolved.json ui/material/tokens/tokens.odin
//
// A colour token becomes the Role its alias chain ends at, not a colour,
// so components follow whatever scheme is active. A token with a standard
// motion mode also gets a <NAME>_STANDARD twin. ref.* tokens are skipped:
// components never read them.
package main

import "core:encoding/json"
import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"

main :: proc() {
	if len(os.args) != 3 {
		fmt.eprintln("usage: material-tokens <m3e.resolved.json> <out.odin>")
		os.exit(2)
	}
	data, err := os.read_entire_file(os.args[1], context.allocator)
	if err != nil {
		fmt.eprintfln("read %s: %v", os.args[1], err)
		os.exit(1)
	}
	doc, jerr := json.parse(data)
	if jerr != nil {
		fmt.eprintfln("parse %s: %v", os.args[1], jerr)
		os.exit(1)
	}
	toks := doc.(json.Object)["tokens"].(json.Object)
	out, ok := generate(toks)
	if !ok {
		os.exit(1)
	}
	if werr := os.write_entire_file(os.args[2], transmute([]u8)out); werr != nil {
		fmt.eprintfln("write %s: %v", os.args[2], werr)
		os.exit(1)
	}
}

generate :: proc(toks: json.Object) -> (string, bool) {
	keys := make([dynamic]string)
	for k in toks {
		append(&keys, k)
	}
	slice.sort(keys[:])

	b := strings.builder_make()
	fmt.sbprint(&b, HEADER)

	// Roles: every sys.color token, in path order.
	roles := make([dynamic]string)
	for k in keys {
		if strings.has_prefix(k, "sys.color.") {
			append(&roles, k)
		}
	}
	fmt.sbprintln(&b, "// Role is one sys.color role. A colour token names the role it aliases.")
	fmt.sbprintln(&b, "Role :: enum u8 {")
	for r in roles {
		fmt.sbprintfln(&b, "\t%s,", role_name(r))
	}
	fmt.sbprintln(&b, "}\n")
	for mode in ([]string{"value", "dark"}) {
		name := mode == "value" ? "LIGHT" : "DARK"
		fmt.sbprintfln(&b, "// %s is the baseline %s scheme, 0xRRGGBB per role.", name, mode == "value" ? "light" : "dark")
		fmt.sbprintfln(&b, "%s :: [Role]u32 {{", name)
		for r in roles {
			t := toks[r].(json.Object)
			v, has := t[mode]
			if !has {
				v = t["value"]
			}
			fmt.sbprintfln(&b, "\t.%s = 0x%s,", role_name(r), strings.trim_prefix(v.(json.String), "#"))
		}
		fmt.sbprintln(&b, "}\n")
	}

	seen := make(map[string]string)
	ok := true
	for k in keys {
		if strings.has_prefix(k, "ref.") || strings.has_prefix(k, "sys.color.") {
			continue
		}
		t := toks[k].(json.Object)
		name := const_name(k)
		if prev, dup := seen[name]; dup {
			fmt.eprintfln("%s and %s both name %s", prev, k, name)
			ok = false
			continue
		}
		seen[name] = k
		line, lok := literal(toks, k, t, "value")
		ok &&= lok
		if line == "" {
			continue
		}
		fmt.sbprintfln(&b, "%s :: %s", name, line)
		if _, has := t["standard"]; has {
			std, sok := literal(toks, k, t, "standard")
			ok &&= sok
			fmt.sbprintfln(&b, "%s_STANDARD :: %s", name, std)
		}
	}
	return strings.to_string(b), ok
}

HEADER :: `// Code generated by tools/material-tokens from the m3e-kit's
// tokens/m3e.resolved.json. DO NOT EDIT; run just material-tokens.

// Package tokens is Material 3 Expressive's design tokens as constants,
// named after their kit path: comp.button-small.container-height is
// BUTTON_SMALL_CONTAINER_HEIGHT and sys.shape.corner.full is
// SYS_SHAPE_CORNER_FULL. Dimensions are dp, durations ms, opacities 0-1.
package tokens

import "jm:ui/design"

// Shape is a corner shape: four radii in dp, [top-start, top-end,
// bottom-end, bottom-start], or full, half the shorter side.
Shape :: struct {
	radii: [4]f32,
	full:  bool,
}

// Type_Style and Bezier are jm:ui/design's: a composite typography token
// (sizes in sp) and a CSS cubic-bezier easing, so a token passes straight
// to design's shaping and easing procs.
Type_Style :: design.Type_Style
Bezier :: design.Bezier

`

// literal is t's mode value as an Odin constant expression, or "" for a
// token with nothing to carry. ok is false for a value it cannot write.
literal :: proc(toks: json.Object, path: string, t: json.Object, mode: string) -> (string, bool) {
	v := t[mode]
	switch t["type"].(json.String) {
	case "color":
		return fmt.aprintf("Role.%s", role_name(color_root(toks, path))), true
	case "dimension", "number", "duration", "fontWeight":
		return fmt.aprintf("f32(%v)", number(v)), true
	case "fontFamily":
		// jm:ui/material draws in whatever faces use_fonts gives it, so a
		// family carries nothing, as long as it is the kit's platform
		// sans-serif; anything else is a change worth hearing about.
		if f := v.(json.String); f != "sans-serif" {
			fmt.eprintfln("%s: font family %q is not sans-serif", path, f)
			return "", false
		}
		return "", true
	case "cubicBezier":
		a := v.(json.Array)
		return fmt.aprintf("Bezier{{%v, %v, %v, %v}}", number(a[0]), number(a[1]), number(a[2]), number(a[3])), true
	case "shape":
		if s, is_str := v.(json.String); is_str {
			if s != "full" {
				fmt.eprintfln("%s: unknown shape keyword %q", path, s)
				return "", false
			}
			return "Shape{full = true}", true
		}
		a := v.(json.Array)
		return fmt.aprintf("Shape{{radii = {{%v, %v, %v, %v}}}}", number(a[0]), number(a[1]), number(a[2]), number(a[3])), true
	case "typography":
		o := v.(json.Object)
		return fmt.aprintf(
			"Type_Style{{weight = %v, size = %v, line_height = %v, tracking = %v}}",
			number(o["fontWeight"]),
			number(o["fontSize"]),
			number(o["lineHeight"]),
			number(o["letterSpacing"]),
		), true
	}
	fmt.eprintfln("%s: unknown type %v", path, t["type"])
	return "", false
}

number :: proc(v: json.Value) -> f64 {
	#partial switch n in v {
	case json.Float:
		return f64(n)
	case json.Integer:
		return f64(n)
	}
	return 0
}

// color_root follows path's alias chain to the sys.color role it ends at.
color_root :: proc(toks: json.Object, path: string) -> string {
	p := path
	for !strings.has_prefix(p, "sys.color.") {
		p = toks[p].(json.Object)["alias"].(json.String)
	}
	return p
}

// const_name is path as an upper snake identifier, comp. dropped.
const_name :: proc(path: string) -> string {
	p := strings.trim_prefix(path, "comp.")
	s, _ := strings.replace_all(strings.to_upper(p), "-", "_")
	s, _ = strings.replace_all(s, ".", "_")
	return s
}

// role_name is sys.color.on-primary as On_Primary.
role_name :: proc(path: string) -> string {
	p := strings.trim_prefix(path, "sys.color.")
	return strings.to_ada_case(p)
}
