// Code generated by jm-sqlgen from schema.sql and queries.sql. DO NOT EDIT.

package todo_queries

import "core:fmt"

import "jm:sqlite3"

// Editing either file without regenerating fails the build here.
#assert(
	#hash(#load("schema.sql", string), "fnv64a") == 0x9adfb0524ddc1b29,
	"schema.sql changed: run jm-sqlgen",
)
#assert(
	#hash(#load("queries.sql", string), "fnv64a") == 0x40dd9f09767ab921,
	"queries.sql changed: run jm-sqlgen",
)

@(private = "file")
TODO_STATE_SQL :: `SELECT done AS "done: bool" FROM todo WHERE id = @id`

// Todo_State_Row is a row of todo_state. Text and blob fields are allocated in the
// allocator the query was given.
Todo_State_Row :: struct {
	done: bool, // annotated, not inferred
}

// Whether todo id exists, and whether it is done.
//
// todo_state is :one in queries.sql.
todo_state :: proc(
	db: sqlite3.Db,
	id: i64,
	allocator := context.allocator,
) -> (
	row: Todo_State_Row,
	found: bool,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		TODO_STATE_SQL,
		id,
		allocator = allocator,
	) or_return
	if sqlite3.next(&stmt) {
		found = true
		row.done = sqlgen_bool(&stmt, 0)
		if stmt.err == nil && sqlite3.next(&stmt) {
			stmt.err = sqlite3.Fault {
				code = .Misuse,
				text = fmt.aprint("todo_state is :one but returned a second row", allocator = allocator),
			}
		}
	}
	if err = sqlite3.finish(&stmt); err != nil {
		return {}, false, err
	}
	return
}

@(private = "file")
COUNTS_SQL :: `SELECT
	COUNT(*) FILTER (WHERE done = 0) AS "active: i64",
	COUNT(*) FILTER (WHERE done = 1) AS "completed: i64"
FROM todo`

// Counts_Row is a row of counts. Text and blob fields are allocated in the
// allocator the query was given.
Counts_Row :: struct {
	active:    i64, // annotated, not inferred
	completed: i64, // annotated, not inferred
}

// How many todos are active and how many done.
//
// counts is :one in queries.sql.
counts :: proc(
	db: sqlite3.Db,
	allocator := context.allocator,
) -> (
	row: Counts_Row,
	found: bool,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		COUNTS_SQL,
		allocator = allocator,
	) or_return
	if sqlite3.next(&stmt) {
		found = true
		row.active = sqlgen_i64(&stmt, 0)
		row.completed = sqlgen_i64(&stmt, 1)
		if stmt.err == nil && sqlite3.next(&stmt) {
			stmt.err = sqlite3.Fault {
				code = .Misuse,
				text = fmt.aprint("counts is :one but returned a second row", allocator = allocator),
			}
		}
	}
	if err = sqlite3.finish(&stmt); err != nil {
		return {}, false, err
	}
	return
}

@(private = "file")
TODOS_SQL :: `SELECT id, title, done AS "done: bool", note
FROM todo
WHERE @filter = 0 OR (@filter = 1 AND done = 0) OR (@filter = 2 AND done = 1)
ORDER BY id`

// Todos_Row is a row of todos. Text and blob fields are allocated in the
// allocator the query was given.
Todos_Row :: struct {
	id:    i64,
	title: string,
	done:  bool, // annotated, not inferred
	note:  Maybe(string),
}

// The todos a filter shows: 0 all, 1 active, 2 completed.
//
// todos is :many in queries.sql.
todos :: proc(
	db: sqlite3.Db,
	filter: i64,
	allocator := context.allocator,
) -> (
	rows: Todos_Rows,
	err: sqlite3.Error,
) {
	rows.stmt = sqlite3.query(
		db,
		TODOS_SQL,
		filter,
		allocator = allocator,
	) or_return
	return
}

// Todos_Rows is the cursor todos returns: step it with todos_next and end it
// with todos_finish, which returns what stopped it.
Todos_Rows :: struct {
	stmt: sqlite3.Stmt,
}

// todos_next reads the next row; ok is false at the end or on a failure.
todos_next :: proc(rows: ^Todos_Rows) -> (row: Todos_Row, ok: bool) {
	if !sqlite3.next(&rows.stmt) {
		return
	}
	row.id = sqlgen_i64(&rows.stmt, 0)
	row.title = sqlgen_string(&rows.stmt, 1)
	row.done = sqlgen_bool(&rows.stmt, 2)
	row.note = sqlgen_maybe_string(&rows.stmt, 3)
	return row, rows.stmt.err == nil
}

todos_finish :: proc(rows: ^Todos_Rows) -> sqlite3.Error {
	return sqlite3.finish(&rows.stmt)
}

@(private = "file")
TAGGED_SQL :: `SELECT t.id, t.title, g.name AS tag
FROM todo t LEFT JOIN tag g ON g.todo_id = t.id
ORDER BY t.id, g.name`

// Tagged_Row is a row of tagged. Text and blob fields are allocated in the
// allocator the query was given.
Tagged_Row :: struct {
	id:    i64,
	title: string,
	tag:   Maybe(string), // Maybe: tag is on the outer side of a join
}

// Each todo with its tags, untagged ones once with no tag.
//
// tagged is :many in queries.sql.
tagged :: proc(
	db: sqlite3.Db,
	allocator := context.allocator,
) -> (
	rows: Tagged_Rows,
	err: sqlite3.Error,
) {
	rows.stmt = sqlite3.query(
		db,
		TAGGED_SQL,
		allocator = allocator,
	) or_return
	return
}

// Tagged_Rows is the cursor tagged returns: step it with tagged_next and end it
// with tagged_finish, which returns what stopped it.
Tagged_Rows :: struct {
	stmt: sqlite3.Stmt,
}

// tagged_next reads the next row; ok is false at the end or on a failure.
tagged_next :: proc(rows: ^Tagged_Rows) -> (row: Tagged_Row, ok: bool) {
	if !sqlite3.next(&rows.stmt) {
		return
	}
	row.id = sqlgen_i64(&rows.stmt, 0)
	row.title = sqlgen_string(&rows.stmt, 1)
	row.tag = sqlgen_maybe_string(&rows.stmt, 2)
	return row, rows.stmt.err == nil
}

tagged_finish :: proc(rows: ^Tagged_Rows) -> sqlite3.Error {
	return sqlite3.finish(&rows.stmt)
}

@(private = "file")
INSERT_SQL :: `INSERT INTO todo(title, note) VALUES (@title, @note)`

// insert is :last_id in queries.sql.
insert :: proc(
	db: sqlite3.Db,
	title: string,
	note: Maybe(string),
	allocator := context.allocator,
) -> (
	n: i64,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		INSERT_SQL,
		title,
		sqlgen_value(note),
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	sqlite3.finish(&stmt) or_return
	return sqlite3.last_id(db), nil
}

@(private = "file")
SET_DONE_SQL :: `UPDATE todo SET done = @done WHERE id = @id`

// set_done is :exec in queries.sql.
set_done :: proc(
	db: sqlite3.Db,
	id: i64,
	done: bool,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		SET_DONE_SQL,
		done,
		id,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

@(private = "file")
SET_ALL_SQL :: `UPDATE todo SET done = @done WHERE done != @done`

// Touches only the rows that differ, so the change batch names only those.
//
// set_all is :rows in queries.sql.
set_all :: proc(
	db: sqlite3.Db,
	done: bool,
	allocator := context.allocator,
) -> (
	n: i64,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		SET_ALL_SQL,
		done,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	sqlite3.finish(&stmt) or_return
	return sqlite3.changes(db), nil
}

@(private = "file")
TAG_SQL :: `INSERT INTO tag(todo_id, name) VALUES (@todo_id, @name) ON CONFLICT DO NOTHING`

// tag is :exec in queries.sql.
tag :: proc(
	db: sqlite3.Db,
	todo_id: i64,
	name: string,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt := sqlite3.query(
		db,
		TAG_SQL,
		todo_id,
		name,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	return sqlite3.finish(&stmt)
}

@(private = "file")
REMOVE_DONE_SQL :: `DELETE FROM todo WHERE done = 1`

// remove_done is :rows in queries.sql.
remove_done :: proc(
	db: sqlite3.Db,
	allocator := context.allocator,
) -> (
	n: i64,
	err: sqlite3.Error,
) {
	stmt := sqlite3.query(
		db,
		REMOVE_DONE_SQL,
		allocator = allocator,
	) or_return
	for sqlite3.next(&stmt) {}
	sqlite3.finish(&stmt) or_return
	return sqlite3.changes(db), nil
}

// check prepares every query against db and compares the parameters and
// columns each has there with those it was generated for, so a database
// whose schema has drifted from schema.sql fails when it is opened rather
// than when a query first runs.
check :: proc(db: sqlite3.Db, allocator := context.allocator) -> sqlite3.Error {
	sqlgen_check(db, "todo_state", TODO_STATE_SQL, 1, {"done: bool"}, allocator) or_return
	sqlgen_check(db, "counts", COUNTS_SQL, 0, {"active: i64", "completed: i64"}, allocator) or_return
	sqlgen_check(db, "todos", TODOS_SQL, 1, {"id", "title", "done: bool", "note"}, allocator) or_return
	sqlgen_check(db, "tagged", TAGGED_SQL, 0, {"id", "title", "tag"}, allocator) or_return
	sqlgen_check(db, "insert", INSERT_SQL, 2, {}, allocator) or_return
	sqlgen_check(db, "set_done", SET_DONE_SQL, 2, {}, allocator) or_return
	sqlgen_check(db, "set_all", SET_ALL_SQL, 1, {}, allocator) or_return
	sqlgen_check(db, "tag", TAG_SQL, 2, {}, allocator) or_return
	sqlgen_check(db, "remove_done", REMOVE_DONE_SQL, 0, {}, allocator) or_return
	return nil
}

@(private = "file")
sqlgen_check :: proc(
	db: sqlite3.Db,
	name, sql: string,
	params: int,
	columns: []string,
	allocator := context.allocator,
) -> sqlite3.Error {
	stmt, err := sqlite3.prepare(db, sql, allocator)
	if f, failed := err.(sqlite3.Fault); failed {
		f.text = fmt.aprintf("%s: %s", name, f.text, allocator = allocator)
		return f
	}
	defer sqlite3.finish(&stmt)
	wrong := ""
	switch {
	case sqlite3.parameter_count(stmt) != params:
		wrong = fmt.aprintf("takes %d parameters", sqlite3.parameter_count(stmt), allocator = allocator)
	case sqlite3.column_count(stmt) != len(columns):
		wrong = fmt.aprintf("returns %d columns", sqlite3.column_count(stmt), allocator = allocator)
	case:
		for want, i in columns {
			if got := sqlite3.name(stmt, i); got != want {
				wrong = fmt.aprintf("names column %d %q", i + 1, got, allocator = allocator)
				break
			}
		}
	}
	if wrong == "" {
		return nil
	}
	return sqlite3.Fault {
		code = .Schema,
		text = fmt.aprintf(
			"%s %s, which is not what it was generated for",
			name,
			wrong,
			allocator = allocator,
		),
	}
}

@(private = "file")
sqlgen_value :: proc(v: Maybe($T)) -> sqlite3.Value {
	if x, ok := v.?; ok {
		return x
	}
	return nil
}

// sqlgen_expect fails the statement unless column col holds want, so a value
// of a type the generated code did not expect stops the read instead of
// converting silently.
@(private = "file")
sqlgen_expect :: proc(stmt: ^sqlite3.Stmt, col: int, want: sqlite3.Type) -> bool {
	got := sqlite3.type_of(stmt^, col)
	if got == want {
		return true
	}
	if stmt.err == nil {
		stmt.err = sqlite3.Fault {
			code = .Mismatch,
			text = fmt.aprintf(
				"column %s holds %v where jm-sqlgen generated %v",
				sqlite3.name(stmt^, col),
				got,
				want,
				allocator = stmt.allocator,
			),
		}
	}
	return false
}

@(private = "file")
sqlgen_i64 :: proc(stmt: ^sqlite3.Stmt, col: int) -> (v: i64) {
	if sqlgen_expect(stmt, col, .Integer) {
		v = sqlite3.integer(stmt^, col)
	}
	return
}

@(private = "file")
sqlgen_bool :: proc(stmt: ^sqlite3.Stmt, col: int) -> (v: bool) {
	if !sqlgen_expect(stmt, col, .Integer) {
		return
	}
	switch n := sqlite3.integer(stmt^, col); n {
	case 0, 1:
		v = n == 1
	case:
		if stmt.err == nil {
			stmt.err = sqlite3.Fault {
				code = .Mismatch,
				text = fmt.aprintf(
					"column %s holds %d, which is not a bool",
					sqlite3.name(stmt^, col),
					n,
					allocator = stmt.allocator,
				),
			}
		}
	}
	return
}

@(private = "file")
sqlgen_string :: proc(stmt: ^sqlite3.Stmt, col: int) -> (v: string) {
	if sqlgen_expect(stmt, col, .Text) {
		v = sqlite3.text(stmt^, col)
	}
	return
}

@(private = "file")
sqlgen_maybe_string :: proc(stmt: ^sqlite3.Stmt, col: int) -> (v: Maybe(string)) {
	if !sqlite3.is_null(stmt^, col) {
		v = sqlgen_string(stmt, col)
	}
	return
}
