// icon-data writes jm:ui/primer/icon_data.odin from @primer/octicons'
// build data (the primer-kit's source/npm/octicons/data.json): every
// octicon becomes an Icon member (triangle-down is Triangle_Down) with its
// path data at each natural height jm:ui/primer draws, 12, 16 and 24px,
// and its width there.
//
//	icon-data tools/primer/source/npm/octicons/data.json ui/primer/icon_data.odin
//
// An icon drawn from several <path>s keeps them apart, a design.Icon_Paths
// entry each, so each fills with its own rule and starts where its own
// first moveto says; an icon of more paths than an entry holds is refused.
package main

import "core:encoding/json"
import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"
import "jm:ui/design"

HEIGHTS :: [3]string{"12", "16", "24"}

main :: proc() {
	if len(os.args) != 3 {
		fmt.eprintln("usage: icon-data <data.json> <out.odin>")
		os.exit(2)
	}
	data, err := os.read_entire_file(os.args[1], context.allocator)
	if err != nil {
		fmt.eprintfln("read %s: %v", os.args[1], err)
		os.exit(1)
	}
	out, ok := generate(data)
	if !ok {
		os.exit(1)
	}
	if werr := os.write_entire_file(os.args[2], transmute([]u8)out); werr != nil {
		fmt.eprintfln("write %s: %v", os.args[2], werr)
		os.exit(1)
	}
}

// Octicon_Path is one <path>: its data and whether it fills even-odd.
Octicon_Path :: struct {
	d:        string,
	even_odd: bool,
}

// Octicon is one icon at the heights drawn: its paths (none where it has
// no design at that height) and width.
Octicon :: struct {
	member: string,
	paths:  [3][]Octicon_Path,
	width:  [3]int,
}

// generate is the Odin source for octicons' data.json.
generate :: proc(data: []u8) -> (string, bool) {
	doc, jerr := json.parse(data)
	if jerr != nil {
		fmt.eprintfln("parse octicons data: %v", jerr)
		return "", false
	}
	icons := make([dynamic]Octicon)
	for name, v in doc.(json.Object) {
		o := Octicon{member = member_name(name)}
		drawn := false
		heights := v.(json.Object)["heights"].(json.Object)
		for h, i in HEIGHTS {
			entry, has := heights[h]
			if !has {
				continue
			}
			e := entry.(json.Object)
			paths := e["paths"].(json.Array)
			if len(paths) > design.ICON_MAX_PATHS {
				fmt.eprintfln("octicon %s-%s has %d paths; an entry holds %d", name, h, len(paths), design.ICON_MAX_PATHS)
				return "", false
			}
			o.paths[i] = make([]Octicon_Path, len(paths))
			for p, j in paths {
				po := p.(json.Object)
				o.paths[i][j] = {po["d"].(json.String), po["evenodd"].(json.Boolean)}
			}
			o.width[i] = int(e["width"].(json.Float))
			drawn = true
		}
		if drawn {
			append(&icons, o)
		}
	}
	slice.sort_by(icons[:], proc(a, b: Octicon) -> bool {return a.member < b.member})
	return emit(icons[:]), true
}

// member_name is triangle-down as Triangle_Down.
member_name :: proc(name: string) -> string {
	parts := strings.split(name, "-")
	for &p in parts {
		p = strings.concatenate({strings.to_upper(p[:1]), p[1:]})
	}
	return strings.join(parts, "_")
}

emit :: proc(icons: []Octicon) -> string {
	b := strings.builder_make()
	fmt.sbprint(&b, HEADER)
	fmt.sbprintln(&b, "package primer\n")
	fmt.sbprintln(&b, "import \"jm:ui/design\"\n")
	fmt.sbprintln(&b, "// Icon is one octicon.")
	fmt.sbprintln(&b, "Icon :: enum u16 {")
	fmt.sbprintln(&b, "\tNone,")
	for ic in icons {
		fmt.sbprintfln(&b, "\t%s,", ic.member)
	}
	fmt.sbprintln(&b, "}\n")
	for h, i in HEIGHTS {
		fmt.sbprintfln(&b, "// ICON_%s is each icon's paths at %spx, none where it has no design there.", h, h)
		fmt.sbprintln(&b, "@(private)")
		fmt.sbprintfln(&b, "ICON_%s := #partial [Icon]design.Icon_Paths {{", h)
		for ic in icons {
			if len(ic.paths[i]) > 0 {
				fmt.sbprintfln(&b, "\t.%s = %s,", ic.member, entry(ic.paths[i]))
			}
		}
		fmt.sbprintln(&b, "}\n")
		fmt.sbprintfln(&b, "// ICON_WIDTH_%s is each icon's width at %spx, where it is not square.", h, h)
		fmt.sbprintln(&b, "@(private)")
		fmt.sbprintfln(&b, "ICON_WIDTH_%s := #partial [Icon]u8 {{", h)
		for ic in icons {
			if len(ic.paths[i]) > 0 && fmt.tprint(ic.width[i]) != h {
				fmt.sbprintfln(&b, "\t.%s = %d,", ic.member, ic.width[i])
			}
		}
		fmt.sbprintln(&b, "}\n")
	}
	return strings.to_string(b)
}

// entry is paths as a design.Icon_Paths literal: {d = {0 = "M…", 1 = "m…"}},
// with even_odd = {1} naming the paths that fill even-odd.
entry :: proc(paths: []Octicon_Path) -> string {
	b := strings.builder_make()
	fmt.sbprint(&b, "{d = {")
	for p, j in paths {
		fmt.sbprintf(&b, "%s%d = %q", j > 0 ? ", " : "", j, p.d)
	}
	fmt.sbprint(&b, "}")
	odd := make([dynamic]string)
	for p, j in paths {
		if p.even_odd {
			append(&odd, fmt.tprint(j))
		}
	}
	if len(odd) > 0 {
		fmt.sbprintf(&b, ", even_odd = {{%s}}", strings.join(odd[:], ", "))
	}
	fmt.sbprint(&b, "}")
	return strings.to_string(b)
}

HEADER :: `// Code generated by tools/primer/icon-data from @primer/octicons' build
// data (MIT, tools/primer/source/npm/octicons/LICENSE, whose README puts
// the GitHub marks under github.com/logos), the primer-kit's
// source/npm/octicons/data.json: each entry is an icon's SVG paths at
// one natural height, each filled on its own with its own rule. DO NOT
// EDIT; run just primer-icons.
`
