// icon-data writes jm:ui/primer/icon_data.odin from @primer/octicons'
// build data (the primer-kit's source/npm/octicons/data.json): every
// octicon becomes an Icon member (triangle-down is Triangle_Down) with its
// path data at each natural height jm:ui/primer draws, 12, 16 and 24px,
// and its width there.
//
//	icon-data tools/primer/source/npm/octicons/data.json ui/primer/icon_data.odin
//
// An icon drawn from several <path>s keeps them as one path's subpaths,
// filled non-zero like the separate paths. A height whose paths fill
// even-odd is left out, since the renderer fills non-zero only; the icon
// keeps its other heights, and the header lists what was dropped.
package main

import "core:encoding/json"
import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"

HEIGHTS :: [3]string{"12", "16", "24"}

main :: proc() {
	if len(os.args) != 3 {
		fmt.eprintln("usage: icon-data <data.json> <out.odin>")
		os.exit(2)
	}
	data, err := os.read_entire_file(os.args[1], context.allocator)
	if err != nil {
		fmt.eprintfln("read %s: %v", os.args[1], err)
		os.exit(1)
	}
	out, ok := generate(data)
	if !ok {
		os.exit(1)
	}
	if werr := os.write_entire_file(os.args[2], transmute([]u8)out); werr != nil {
		fmt.eprintfln("write %s: %v", os.args[2], werr)
		os.exit(1)
	}
}

// Octicon is one icon at the heights drawn: its path data ("" where it has
// no design at that height, or one that fills even-odd) and width.
Octicon :: struct {
	member: string,
	d:      [3]string,
	width:  [3]int,
}

// generate is the Odin source for octicons' data.json.
generate :: proc(data: []u8) -> (string, bool) {
	doc, jerr := json.parse(data)
	if jerr != nil {
		fmt.eprintfln("parse octicons data: %v", jerr)
		return "", false
	}
	icons := make([dynamic]Octicon)
	dropped := make([dynamic]string)
	for name, v in doc.(json.Object) {
		o := Octicon{member = member_name(name)}
		heights := v.(json.Object)["heights"].(json.Object)
		for h, i in HEIGHTS {
			entry, has := heights[h]
			if !has {
				continue
			}
			e := entry.(json.Object)
			if e["evenodd"].(json.Boolean) {
				append(&dropped, fmt.aprintf("%s-%s", name, h))
				continue
			}
			paths := e["d"].(json.Array)
			ds := make([]string, len(paths))
			for p, j in paths {
				ds[j] = p.(json.String)
			}
			o.d[i] = strings.join(ds, " ")
			o.width[i] = int(e["width"].(json.Float))
		}
		if o.d == {} {
			continue
		}
		append(&icons, o)
	}
	slice.sort_by(icons[:], proc(a, b: Octicon) -> bool {return a.member < b.member})
	slice.sort(dropped[:])
	return emit(icons[:], dropped[:]), true
}

// member_name is triangle-down as Triangle_Down.
member_name :: proc(name: string) -> string {
	parts := strings.split(name, "-")
	for &p in parts {
		p = strings.concatenate({strings.to_upper(p[:1]), p[1:]})
	}
	return strings.join(parts, "_")
}

emit :: proc(icons: []Octicon, dropped: []string) -> string {
	b := strings.builder_make()
	fmt.sbprint(&b, HEADER)
	fmt.sbprint(&b, wrap_comment(fmt.tprintf("Left out, filling even-odd: %s.", strings.join(dropped, ", "))))
	fmt.sbprintln(&b, "package primer\n")
	fmt.sbprintln(&b, "// Icon is one octicon.")
	fmt.sbprintln(&b, "Icon :: enum u16 {")
	fmt.sbprintln(&b, "\tNone,")
	for ic in icons {
		fmt.sbprintfln(&b, "\t%s,", ic.member)
	}
	fmt.sbprintln(&b, "}\n")
	for h, i in HEIGHTS {
		fmt.sbprintfln(&b, "// ICON_%s is each icon's path data at %spx, \"\" where it has none.", h, h)
		fmt.sbprintln(&b, "@(private)")
		fmt.sbprintfln(&b, "ICON_%s := #partial [Icon]string {{", h)
		for ic in icons {
			if ic.d[i] != "" {
				fmt.sbprintfln(&b, "\t.%s = %q,", ic.member, ic.d[i])
			}
		}
		fmt.sbprintln(&b, "}\n")
		fmt.sbprintfln(&b, "// ICON_WIDTH_%s is each icon's width at %spx, where it is not square.", h, h)
		fmt.sbprintln(&b, "@(private)")
		fmt.sbprintfln(&b, "ICON_WIDTH_%s := #partial [Icon]u8 {{", h)
		for ic in icons {
			if ic.d[i] != "" && fmt.tprint(ic.width[i]) != h {
				fmt.sbprintfln(&b, "\t.%s = %d,", ic.member, ic.width[i])
			}
		}
		fmt.sbprintln(&b, "}\n")
	}
	return strings.to_string(b)
}

// wrap_comment is s as // lines of at most 72 columns, broken at spaces.
wrap_comment :: proc(s: string) -> string {
	b := strings.builder_make()
	line := 0
	for w in strings.split(s, " ") {
		if line > 0 && line + 1 + len(w) > 72 {
			fmt.sbprintln(&b)
			line = 0
		}
		if line == 0 {
			fmt.sbprint(&b, "//")
			line = 2
		}
		fmt.sbprintf(&b, " %s", w)
		line += 1 + len(w)
	}
	fmt.sbprintln(&b)
	return strings.to_string(b)
}

HEADER :: `// Code generated by tools/primer/icon-data from @primer/octicons' build
// data (MIT, tools/primer/source/npm/octicons/LICENSE, whose README puts
// the GitHub marks under github.com/logos), the primer-kit's
// source/npm/octicons/data.json: each entry is an icon's SVG path data at
// one natural height, its paths joined as subpaths. DO NOT EDIT; run
// just primer-icons.
`
