// material-shapes writes jm:ui/material's shape data from the m3e-kit's
// shapes/morphs.json: the loading indicator's pre-matched morph pairs, as
// Odin constants in package material.
//
//	material-shapes <m3e-kit>/shapes/morphs.json ui/material/shape_data.odin
//
// morphs.json's notes say each pair is Morph(a, b) from graphics-shapes
// 1.0.1, sampled at 0 and 1, so the matching Morph does is already done
// and the generated pairs need only a per-point lerp at runtime. generate
// checks the part of that it can: each pair's two ends have the same
// number of cubics.
package main

import "core:encoding/json"
import "core:fmt"
import "core:os"
import "core:strings"

main :: proc() {
	if len(os.args) != 3 {
		fmt.eprintln("usage: material-shapes <morphs.json> <out.odin>")
		os.exit(2)
	}
	data, err := os.read_entire_file(os.args[1], context.allocator)
	if err != nil {
		fmt.eprintfln("read %s: %v", os.args[1], err)
		os.exit(1)
	}
	doc, jerr := json.parse(data)
	if jerr != nil {
		fmt.eprintfln("parse %s: %v", os.args[1], jerr)
		os.exit(1)
	}
	out, ok := generate(doc.(json.Object))
	if !ok {
		os.exit(1)
	}
	if werr := os.write_entire_file(os.args[2], transmute([]u8)out); werr != nil {
		fmt.eprintfln("write %s: %v", os.args[2], werr)
		os.exit(1)
	}
}

// generate is the Odin source for morphs, the parsed morphs.json. ok is
// false, with the reason printed, for a document it cannot carry: a
// missing sequence, a pair whose start and end differ in length, or a
// cubic without eight numbers.
generate :: proc(morphs: json.Object) -> (string, bool) {
	b := strings.builder_make()
	fmt.sbprint(&b, HEADER)
	if src, has := morphs["source"].(json.Object); has {
		fmt.sbprintfln(&b, "// Source: %v at androidx %v.\n", src["file"], src["commit"])
	}
	ok := true
	for mode in ([]string{"indeterminate", "determinate"}) {
		seq, has := morphs[mode].(json.Object)
		if !has {
			fmt.eprintfln("morphs.json has no %s sequence", mode)
			ok = false
			continue
		}
		ok &&= sequence(&b, mode, seq)
	}
	return strings.to_string(b), ok
}

HEADER :: `// Code generated by tools/material-shapes from the m3e-kit's
// shapes/morphs.json. DO NOT EDIT; run just material-shapes.

package material

// Shape_Cubic is one cubic Bézier of a Material shape outline in the unit
// square, y down: anchor, control, control, anchor as
// [x0, y0, c1x, c1y, c2x, c2y, x1, y1]. Each cubic ends where the next
// begins, and the last returns to the first point.
Shape_Cubic :: [8]f32

// Shape_Morph is a pair of shapes pre-matched by graphics-shapes' Morph:
// start and end have equal length, and the morph at t is start + (end -
// start) * t per number, drawn like a shape. t may overshoot [0, 1].
Shape_Morph :: struct {
	from, to:   string,
	start, end: []Shape_Cubic,
}

// Loading_Sequence is one loading indicator mode: its morphs in order,
// whether the last wraps to the first, and its bounds-fit scales.
// draw_scale times the container's shorter side is the drawn shape's size.
Loading_Sequence :: struct {
	morphs:                 []Shape_Morph,
	circular:               bool,
	shapes_scale_factor:    f32,
	active_indicator_scale: f32,
	draw_scale:             f32,
}

`

// sequence writes one mode as LOADING_<MODE> :: Loading_Sequence.
sequence :: proc(b: ^strings.Builder, mode: string, seq: json.Object) -> bool {
	name := strings.to_upper(mode)
	names := seq["sequence"].(json.Array)
	fmt.sbprintf(b, "// LOADING_%s is the %s loading indicator's morphs:", name, mode)
	for n, i in names {
		fmt.sbprintf(b, "%s %v", i == 0 ? "" : ",", n)
	}
	circular := seq["circular"].(json.Boolean)
	fmt.sbprintfln(b, "%s.", circular ? ", then back to the first" : "")
	fmt.sbprintfln(b, "LOADING_%s := Loading_Sequence {{", name)
	fmt.sbprintln(b, "\tmorphs = []Shape_Morph {")
	ok := true
	for pv in seq["pairs"].(json.Array) {
		p := pv.(json.Object)
		start, end := p["start"].(json.Array), p["end"].(json.Array)
		if len(start) != len(end) {
			fmt.eprintfln("%s %v -> %v: start has %d cubics, end %d", mode, p["from"], p["to"], len(start), len(end))
			ok = false
			continue
		}
		fmt.sbprintfln(b, "\t\t{{\n\t\t\tfrom = %q,\n\t\t\tto = %q,", p["from"].(json.String), p["to"].(json.String))
		for side in ([]string{"start", "end"}) {
			fmt.sbprintfln(b, "\t\t\t%s = []Shape_Cubic {{", side)
			for cv in p[side].(json.Array) {
				c := cv.(json.Array)
				if len(c) != 8 {
					fmt.eprintfln("%s %v -> %v: a cubic has %d numbers, not 8", mode, p["from"], p["to"], len(c))
					ok = false
					continue
				}
				fmt.sbprint(b, "\t\t\t\t{")
				for v, i in c {
					fmt.sbprintf(b, "%s%v", i == 0 ? "" : ", ", number(v))
				}
				fmt.sbprintln(b, "},")
			}
			fmt.sbprintln(b, "\t\t\t},")
		}
		fmt.sbprintln(b, "\t\t},")
	}
	fmt.sbprintln(b, "\t},")
	fmt.sbprintfln(b, "\tcircular = %v,", circular)
	fmt.sbprintfln(b, "\tshapes_scale_factor = %v,", number(seq["shapesScaleFactor"]))
	fmt.sbprintfln(b, "\tactive_indicator_scale = %v,", number(seq["activeIndicatorScale"]))
	fmt.sbprintfln(b, "\tdraw_scale = %v,", number(seq["drawScale"]))
	fmt.sbprintln(b, "}\n")
	return ok
}

// number is v as an f64, whether json parsed it as an integer or a float:
// a copy of tools/design-tokens' number, as each tool is its own main
// package.
number :: proc(v: json.Value) -> f64 {
	#partial switch n in v {
	case json.Float:
		return f64(n)
	case json.Integer:
		return f64(n)
	}
	return 0
}
