/*
The raw C API under the C names, exported so a caller that needs an interface
the wrapper does not cover can reach for it. The wrapper in zstd.odin is what
scripts should use. The declarations track the vendored headers of zstd
1.5.7: all of zstd.h's stable API, zstd_errors.h, zdict.h's stable API, and
from the experimental section only the ZSTD_customMem constructors, which
route zstd's allocations to an Odin allocator. Experimental symbols are safe
here because the library is linked statically at a pinned version.

The library is the single-file amalgamation under vendor/, generated by
zstd's build/single_file_libs/create_single_file_library.sh and compiled into
lib/ by the justfile's `zstd` recipe. The archive path below is relative to
this directory, which is what puts lib/ here rather than in build/.
*/
package zstd

import "core:c"

when ODIN_OS == .Windows {
	foreign import lib "lib/zstd.lib"
} else when ODIN_OS == .Darwin {
	// libpthread is part of libSystem: the macOS tests link without -lpthread.
	foreign import lib "lib/zstd.a"
} else {
	@(extra_linker_flags = "-lpthread")
	foreign import lib "lib/zstd.a"
}

VERSION_MAJOR :: 1
VERSION_MINOR :: 5
VERSION_RELEASE :: 7
VERSION_NUMBER :: VERSION_MAJOR * 100 * 100 + VERSION_MINOR * 100 + VERSION_RELEASE

CLEVEL_DEFAULT :: 3
MAGICNUMBER :: 0xFD2FB528
MAGIC_DICTIONARY :: 0xEC30A437
MAGIC_SKIPPABLE_START :: 0x184D2A50
MAGIC_SKIPPABLE_MASK :: 0xFFFFFFF0
BLOCKSIZELOG_MAX :: 17
BLOCKSIZE_MAX :: 1 << BLOCKSIZELOG_MAX
CONTENTSIZE_UNKNOWN :: ~c.ulonglong(0)
CONTENTSIZE_ERROR :: ~c.ulonglong(0) - 1

// The window limits from zstd.h's experimental section, which the wrapper
// needs to clamp a window to what the library accepts.
WINDOWLOG_MAX :: 30 when size_of(uintptr) == 4 else 31
WINDOWLOG_MIN :: 10
WINDOWLOG_LIMIT_DEFAULT :: 27

// ZSTD_CCtx and ZSTD_DCtx are opaque; zstd owns their memory. The stream
// types are the same objects since v1.3.0.
ZSTD_CCtx :: struct {}
ZSTD_DCtx :: struct {}
ZSTD_CStream :: ZSTD_CCtx
ZSTD_DStream :: ZSTD_DCtx
ZSTD_CDict :: struct {}
ZSTD_DDict :: struct {}

ZSTD_ErrorCode :: enum c.int {
	no_error                              = 0,
	GENERIC                               = 1,
	prefix_unknown                        = 10,
	version_unsupported                   = 12,
	frameParameter_unsupported            = 14,
	frameParameter_windowTooLarge         = 16,
	corruption_detected                   = 20,
	checksum_wrong                        = 22,
	literals_headerWrong                  = 24,
	dictionary_corrupted                  = 30,
	dictionary_wrong                      = 32,
	dictionaryCreation_failed             = 34,
	parameter_unsupported                 = 40,
	parameter_combination_unsupported     = 41,
	parameter_outOfBound                  = 42,
	tableLog_tooLarge                     = 44,
	maxSymbolValue_tooLarge               = 46,
	maxSymbolValue_tooSmall               = 48,
	cannotProduce_uncompressedBlock       = 49,
	stabilityCondition_notRespected       = 50,
	stage_wrong                           = 60,
	init_missing                          = 62,
	memory_allocation                     = 64,
	workSpace_tooSmall                    = 66,
	dstSize_tooSmall                      = 70,
	srcSize_wrong                         = 72,
	dstBuffer_null                        = 74,
	noForwardProgress_destFull            = 80,
	noForwardProgress_inputEmpty          = 82,
	frameIndex_tooLarge                   = 100,
	seekableIO                            = 102,
	dstBuffer_wrong                       = 104,
	srcBuffer_wrong                       = 105,
	sequenceProducer_failed               = 106,
	externalSequences_invalid             = 107,
	maxCode                               = 120,
}

ZSTD_strategy :: enum c.int {
	fast     = 1,
	dfast    = 2,
	greedy   = 3,
	lazy     = 4,
	lazy2    = 5,
	btlazy2  = 6,
	btopt    = 7,
	btultra  = 8,
	btultra2 = 9,
}

ZSTD_cParameter :: enum c.int {
	compressionLevel           = 100,
	windowLog                  = 101,
	hashLog                    = 102,
	chainLog                   = 103,
	searchLog                  = 104,
	minMatch                   = 105,
	targetLength               = 106,
	strategy                   = 107,
	targetCBlockSize           = 130,
	enableLongDistanceMatching = 160,
	ldmHashLog                 = 161,
	ldmMinMatch                = 162,
	ldmBucketSizeLog           = 163,
	ldmHashRateLog             = 164,
	contentSizeFlag            = 200,
	checksumFlag               = 201,
	dictIDFlag                 = 202,
	nbWorkers                  = 400,
	jobSize                    = 401,
	overlapLog                 = 402,
}

ZSTD_dParameter :: enum c.int {
	windowLogMax = 100,
}

ZSTD_ResetDirective :: enum c.int {
	session_only           = 1,
	parameters             = 2,
	session_and_parameters = 3,
}

ZSTD_EndDirective :: enum c.int {
	continue_ = 0,
	flush     = 1,
	end       = 2,
}

ZSTD_bounds :: struct {
	error:      c.size_t,
	lowerBound: c.int,
	upperBound: c.int,
}

ZSTD_inBuffer :: struct {
	src:  rawptr,
	size: c.size_t,
	pos:  c.size_t,
}

ZSTD_outBuffer :: struct {
	dst:  rawptr,
	size: c.size_t,
	pos:  c.size_t,
}

ZSTD_allocFunction :: #type proc "c" (opaque: rawptr, size: c.size_t) -> rawptr
ZSTD_freeFunction :: #type proc "c" (opaque: rawptr, address: rawptr)

ZSTD_customMem :: struct {
	customAlloc: ZSTD_allocFunction,
	customFree:  ZSTD_freeFunction,
	opaque:      rawptr,
}

ZDICT_params_t :: struct {
	compressionLevel:  c.int,
	notificationLevel: c.uint,
	dictID:            c.uint,
}

@(default_calling_convention = "c")
foreign lib {
	ZSTD_versionNumber :: proc() -> c.uint ---
	ZSTD_versionString :: proc() -> cstring ---

	ZSTD_compress                :: proc(dst: rawptr, dstCapacity: c.size_t, src: rawptr, srcSize: c.size_t, compressionLevel: c.int) -> c.size_t ---
	ZSTD_decompress              :: proc(dst: rawptr, dstCapacity: c.size_t, src: rawptr, compressedSize: c.size_t) -> c.size_t ---
	ZSTD_getFrameContentSize     :: proc(src: rawptr, srcSize: c.size_t) -> c.ulonglong ---
	ZSTD_findFrameCompressedSize :: proc(src: rawptr, srcSize: c.size_t) -> c.size_t ---
	ZSTD_compressBound           :: proc(srcSize: c.size_t) -> c.size_t ---

	ZSTD_isError       :: proc(result: c.size_t) -> c.uint ---
	ZSTD_getErrorCode  :: proc(functionResult: c.size_t) -> ZSTD_ErrorCode ---
	ZSTD_getErrorName  :: proc(result: c.size_t) -> cstring ---
	ZSTD_getErrorString :: proc(code: ZSTD_ErrorCode) -> cstring ---
	ZSTD_minCLevel     :: proc() -> c.int ---
	ZSTD_maxCLevel     :: proc() -> c.int ---
	ZSTD_defaultCLevel :: proc() -> c.int ---

	ZSTD_createCCtx   :: proc() -> ^ZSTD_CCtx ---
	ZSTD_freeCCtx     :: proc(cctx: ^ZSTD_CCtx) -> c.size_t ---
	ZSTD_compressCCtx :: proc(cctx: ^ZSTD_CCtx, dst: rawptr, dstCapacity: c.size_t, src: rawptr, srcSize: c.size_t, compressionLevel: c.int) -> c.size_t ---

	ZSTD_createDCtx     :: proc() -> ^ZSTD_DCtx ---
	ZSTD_freeDCtx       :: proc(dctx: ^ZSTD_DCtx) -> c.size_t ---
	ZSTD_decompressDCtx :: proc(dctx: ^ZSTD_DCtx, dst: rawptr, dstCapacity: c.size_t, src: rawptr, srcSize: c.size_t) -> c.size_t ---

	ZSTD_cParam_getBounds      :: proc(cParam: ZSTD_cParameter) -> ZSTD_bounds ---
	ZSTD_CCtx_setParameter     :: proc(cctx: ^ZSTD_CCtx, param: ZSTD_cParameter, value: c.int) -> c.size_t ---
	ZSTD_CCtx_setPledgedSrcSize :: proc(cctx: ^ZSTD_CCtx, pledgedSrcSize: c.ulonglong) -> c.size_t ---
	ZSTD_CCtx_reset            :: proc(cctx: ^ZSTD_CCtx, reset: ZSTD_ResetDirective) -> c.size_t ---
	ZSTD_compress2             :: proc(cctx: ^ZSTD_CCtx, dst: rawptr, dstCapacity: c.size_t, src: rawptr, srcSize: c.size_t) -> c.size_t ---

	ZSTD_dParam_getBounds  :: proc(dParam: ZSTD_dParameter) -> ZSTD_bounds ---
	ZSTD_DCtx_setParameter :: proc(dctx: ^ZSTD_DCtx, param: ZSTD_dParameter, value: c.int) -> c.size_t ---
	ZSTD_DCtx_reset        :: proc(dctx: ^ZSTD_DCtx, reset: ZSTD_ResetDirective) -> c.size_t ---

	ZSTD_createCStream    :: proc() -> ^ZSTD_CStream ---
	ZSTD_freeCStream      :: proc(zcs: ^ZSTD_CStream) -> c.size_t ---
	ZSTD_compressStream2  :: proc(cctx: ^ZSTD_CCtx, output: ^ZSTD_outBuffer, input: ^ZSTD_inBuffer, endOp: ZSTD_EndDirective) -> c.size_t ---
	ZSTD_CStreamInSize    :: proc() -> c.size_t ---
	ZSTD_CStreamOutSize   :: proc() -> c.size_t ---
	ZSTD_initCStream      :: proc(zcs: ^ZSTD_CStream, compressionLevel: c.int) -> c.size_t ---
	ZSTD_compressStream   :: proc(zcs: ^ZSTD_CStream, output: ^ZSTD_outBuffer, input: ^ZSTD_inBuffer) -> c.size_t ---
	ZSTD_flushStream      :: proc(zcs: ^ZSTD_CStream, output: ^ZSTD_outBuffer) -> c.size_t ---
	ZSTD_endStream        :: proc(zcs: ^ZSTD_CStream, output: ^ZSTD_outBuffer) -> c.size_t ---

	ZSTD_createDStream     :: proc() -> ^ZSTD_DStream ---
	ZSTD_freeDStream       :: proc(zds: ^ZSTD_DStream) -> c.size_t ---
	ZSTD_initDStream       :: proc(zds: ^ZSTD_DStream) -> c.size_t ---
	ZSTD_decompressStream  :: proc(zds: ^ZSTD_DStream, output: ^ZSTD_outBuffer, input: ^ZSTD_inBuffer) -> c.size_t ---
	ZSTD_DStreamInSize     :: proc() -> c.size_t ---
	ZSTD_DStreamOutSize    :: proc() -> c.size_t ---

	ZSTD_compress_usingDict   :: proc(ctx: ^ZSTD_CCtx, dst: rawptr, dstCapacity: c.size_t, src: rawptr, srcSize: c.size_t, dict: rawptr, dictSize: c.size_t, compressionLevel: c.int) -> c.size_t ---
	ZSTD_decompress_usingDict :: proc(dctx: ^ZSTD_DCtx, dst: rawptr, dstCapacity: c.size_t, src: rawptr, srcSize: c.size_t, dict: rawptr, dictSize: c.size_t) -> c.size_t ---

	ZSTD_createCDict          :: proc(dictBuffer: rawptr, dictSize: c.size_t, compressionLevel: c.int) -> ^ZSTD_CDict ---
	ZSTD_freeCDict            :: proc(CDict: ^ZSTD_CDict) -> c.size_t ---
	ZSTD_compress_usingCDict  :: proc(cctx: ^ZSTD_CCtx, dst: rawptr, dstCapacity: c.size_t, src: rawptr, srcSize: c.size_t, cdict: ^ZSTD_CDict) -> c.size_t ---
	ZSTD_createDDict          :: proc(dictBuffer: rawptr, dictSize: c.size_t) -> ^ZSTD_DDict ---
	ZSTD_freeDDict            :: proc(ddict: ^ZSTD_DDict) -> c.size_t ---
	ZSTD_decompress_usingDDict :: proc(dctx: ^ZSTD_DCtx, dst: rawptr, dstCapacity: c.size_t, src: rawptr, srcSize: c.size_t, ddict: ^ZSTD_DDict) -> c.size_t ---

	ZSTD_getDictID_fromDict  :: proc(dict: rawptr, dictSize: c.size_t) -> c.uint ---
	ZSTD_getDictID_fromCDict :: proc(cdict: ^ZSTD_CDict) -> c.uint ---
	ZSTD_getDictID_fromDDict :: proc(ddict: ^ZSTD_DDict) -> c.uint ---
	ZSTD_getDictID_fromFrame :: proc(src: rawptr, srcSize: c.size_t) -> c.uint ---

	ZSTD_CCtx_loadDictionary :: proc(cctx: ^ZSTD_CCtx, dict: rawptr, dictSize: c.size_t) -> c.size_t ---
	ZSTD_CCtx_refCDict       :: proc(cctx: ^ZSTD_CCtx, cdict: ^ZSTD_CDict) -> c.size_t ---
	ZSTD_CCtx_refPrefix      :: proc(cctx: ^ZSTD_CCtx, prefix: rawptr, prefixSize: c.size_t) -> c.size_t ---
	ZSTD_DCtx_loadDictionary :: proc(dctx: ^ZSTD_DCtx, dict: rawptr, dictSize: c.size_t) -> c.size_t ---
	ZSTD_DCtx_refDDict       :: proc(dctx: ^ZSTD_DCtx, ddict: ^ZSTD_DDict) -> c.size_t ---
	ZSTD_DCtx_refPrefix      :: proc(dctx: ^ZSTD_DCtx, prefix: rawptr, prefixSize: c.size_t) -> c.size_t ---

	ZSTD_sizeof_CCtx    :: proc(cctx: ^ZSTD_CCtx) -> c.size_t ---
	ZSTD_sizeof_DCtx    :: proc(dctx: ^ZSTD_DCtx) -> c.size_t ---
	ZSTD_sizeof_CStream :: proc(zcs: ^ZSTD_CStream) -> c.size_t ---
	ZSTD_sizeof_DStream :: proc(zds: ^ZSTD_DStream) -> c.size_t ---
	ZSTD_sizeof_CDict   :: proc(cdict: ^ZSTD_CDict) -> c.size_t ---
	ZSTD_sizeof_DDict   :: proc(ddict: ^ZSTD_DDict) -> c.size_t ---

	// Experimental: allocation through a caller's functions.
	ZSTD_createCCtx_advanced    :: proc(customMem: ZSTD_customMem) -> ^ZSTD_CCtx ---
	ZSTD_createCStream_advanced :: proc(customMem: ZSTD_customMem) -> ^ZSTD_CStream ---
	ZSTD_createDCtx_advanced    :: proc(customMem: ZSTD_customMem) -> ^ZSTD_DCtx ---
	ZSTD_createDStream_advanced :: proc(customMem: ZSTD_customMem) -> ^ZSTD_DStream ---

	ZDICT_trainFromBuffer    :: proc(dictBuffer: rawptr, dictBufferCapacity: c.size_t, samplesBuffer: rawptr, samplesSizes: [^]c.size_t, nbSamples: c.uint) -> c.size_t ---
	ZDICT_finalizeDictionary :: proc(dstDictBuffer: rawptr, maxDictSize: c.size_t, dictContent: rawptr, dictContentSize: c.size_t, samplesBuffer: rawptr, samplesSizes: [^]c.size_t, nbSamples: c.uint, parameters: ZDICT_params_t) -> c.size_t ---
	ZDICT_getDictID          :: proc(dictBuffer: rawptr, dictSize: c.size_t) -> c.uint ---
	ZDICT_getDictHeaderSize  :: proc(dictBuffer: rawptr, dictSize: c.size_t) -> c.size_t ---
	ZDICT_isError            :: proc(errorCode: c.size_t) -> c.uint ---
	ZDICT_getErrorName       :: proc(errorCode: c.size_t) -> cstring ---
}
