// Code generated by jm-sqlgen from schema.sql and queries.sql. DO NOT EDIT.

package notes_pg_queries

import "core:fmt"

import "jm:pq"

// Editing either file without regenerating fails the build here.
#assert(
	#hash(#load("schema.sql", string), "fnv64a") == 0x2503c41ebdd8c5dd,
	"schema.sql changed: run jm-sqlgen",
)
#assert(
	#hash(#load("queries.sql", string), "fnv64a") == 0x05af6ced821efda3,
	"queries.sql changed: run jm-sqlgen",
)

@(private = "file")
NOTE_SQL :: `SELECT body, pinned, rank, score, price, uid, at, mood, attachment
FROM note WHERE id = $1`

// Note_Row is a row of note. Text and blob fields are allocated in the
// allocator the query was given.
Note_Row :: struct {
	body:       string,
	pinned:     bool,
	rank:       i32,
	score:      f64,
	price:      Maybe(string),
	uid:        string,
	at:         string,
	mood:       string,
	attachment: Maybe([]byte),
}

// The note with id, if there is one.
//
// note is :one in queries.sql.
note :: proc(
	db: ^pq.Conn,
	id: i64,
	allocator := context.allocator,
) -> (
	row: Note_Row,
	found: bool,
	err: pq.Error,
) {
	res := pq.exec_values(
		db,
		NOTE_SQL,
		{id},
		allocator,
	) or_return
	defer pq.destroy(&res)
	if len(res.rows) > 1 {
		second := fmt.aprint("note is :one but returned a second row", allocator = allocator)
		return {}, false, pq.Fault{message = second}
	}
	if len(res.rows) == 0 {
		return
	}
	cells := res.rows[0]
	row.body = pq.read_exact(cells[0], "body", string, &err, allocator)
	row.pinned = pq.read_exact(cells[1], "pinned", bool, &err, allocator)
	row.rank = pq.read_exact(cells[2], "rank", i32, &err, allocator)
	row.score = pq.read_exact(cells[3], "score", f64, &err, allocator)
	row.price = pq.read_exact_maybe(cells[4], "price", string, &err, allocator)
	row.uid = pq.read_exact(cells[5], "uid", string, &err, allocator)
	row.at = pq.read_exact(cells[6], "at", string, &err, allocator)
	row.mood = pq.read_exact(cells[7], "mood", string, &err, allocator)
	row.attachment = pq.read_exact_maybe(cells[8], "attachment", []byte, &err, allocator)
	if err != nil {
		note_free_row(row, allocator)
		return {}, false, err
	}
	return row, true, nil
}

// note_free_row frees the text and blobs of row, which are in allocator.
note_free_row :: proc(row: Note_Row, allocator := context.allocator) {
	delete(row.body, allocator)
	if v, ok := row.price.?; ok {
		delete(v, allocator)
	}
	delete(row.uid, allocator)
	delete(row.at, allocator)
	delete(row.mood, allocator)
	if v, ok := row.attachment.?; ok {
		delete(v, allocator)
	}
}

@(private = "file")
TOTALS_SQL :: `SELECT count(*) AS "notes: i64", sum(score) AS score FROM note`

// Totals_Row is a row of totals. Text and blob fields are allocated in the
// allocator the query was given.
Totals_Row :: struct {
	notes: i64, // annotated, not inferred
	score: Maybe(f64), // Maybe: an expression, which PostgreSQL does not say is NOT NULL
}

// How many notes there are, and their summed score, which is NULL when
// there are none.
//
// totals is :one in queries.sql.
totals :: proc(
	db: ^pq.Conn,
	allocator := context.allocator,
) -> (
	row: Totals_Row,
	found: bool,
	err: pq.Error,
) {
	res := pq.exec_values(
		db,
		TOTALS_SQL,
		{},
		allocator,
	) or_return
	defer pq.destroy(&res)
	if len(res.rows) > 1 {
		second := fmt.aprint("totals is :one but returned a second row", allocator = allocator)
		return {}, false, pq.Fault{message = second}
	}
	if len(res.rows) == 0 {
		return
	}
	cells := res.rows[0]
	row.notes = pq.read_exact(cells[0], "notes", i64, &err, allocator)
	row.score = pq.read_exact_maybe(cells[1], "score", f64, &err, allocator)
	if err != nil {
		totals_free_row(row, allocator)
		return {}, false, err
	}
	return row, true, nil
}

// totals_free_row frees the text and blobs of row, which are in allocator.
totals_free_row :: proc(row: Totals_Row, allocator := context.allocator) {
}

@(private = "file")
LABELLED_SQL :: `SELECT n.id, n.body, l.name AS label
FROM note n LEFT JOIN label l ON l.note_id = n.id
ORDER BY n.id, l.name`

// Labelled_Row is a row of labelled. Text and blob fields are allocated in the
// allocator the query was given.
Labelled_Row :: struct {
	id:    i64,
	body:  string,
	label: Maybe(string), // Maybe: label is on the outer side of a join
}

// Labelled_Rows is a cursor over the rows of labelled. err is what stopped it, once it
// is closed: a failed start, a failed step, or a value of the wrong type.
Labelled_Rows :: struct {
	result: pq.Result,
	at:     int,
	err:    pq.Error,
}

// Each note with its labels, an unlabelled one once with no label.
//
// labelled is :many in queries.sql: labelled_open as a guard. Written
// `if labelled(&rows, db, ...) { for row in labelled_next(&rows) { ... } }`, it closes
// the cursor at the end of the if and leaves what stopped it in rows.err,
// which a deferred close cannot return. It is false if the query cannot start.
@(deferred_in = labelled_guard_close)
labelled :: proc(
	rows: ^Labelled_Rows,
	db: ^pq.Conn,
	allocator := context.allocator,
) -> bool {
	opened, err := labelled_open(db, allocator)
	rows^ = opened
	rows.err = err
	return err == nil
}

@(private = "file")
labelled_guard_close :: proc(
	rows: ^Labelled_Rows,
	db: ^pq.Conn,
	allocator := context.allocator,
) {
	labelled_close(rows)
}

// labelled_open starts labelled: step the cursor with labelled_next and end it with
// labelled_close. Text and blobs are allocated in allocator.
labelled_open :: proc(
	db: ^pq.Conn,
	allocator := context.allocator,
) -> (
	rows: Labelled_Rows,
	err: pq.Error,
) {
	rows.result = pq.exec_values(
		db,
		LABELLED_SQL,
		{},
		allocator,
	) or_return
	return
}

// labelled_next reads the next row; ok is false at the end or on a failure.
labelled_next :: proc(rows: ^Labelled_Rows) -> (row: Labelled_Row, ok: bool) {
	if rows.err != nil || rows.at >= len(rows.result.rows) {
		return
	}
	cells := rows.result.rows[rows.at]
	rows.at += 1
	row.id = pq.read_exact(cells[0], "id", i64, &rows.err, rows.result.allocator)
	row.body = pq.read_exact(cells[1], "body", string, &rows.err, rows.result.allocator)
	row.label = pq.read_exact_maybe(cells[2], "label", string, &rows.err, rows.result.allocator)
	if rows.err != nil {
		labelled_free_row(row, rows.result.allocator)
		return {}, false
	}
	return row, true
}

// labelled_close ends the cursor and returns what stopped it, which it also
// keeps in rows.err. Closing twice is safe.
labelled_close :: proc(rows: ^Labelled_Rows) -> pq.Error {
	pq.destroy(&rows.result)
	return rows.err
}

// labelled_all reads every row of labelled into a slice in allocator, with their
// text and blobs; free it with labelled_free. On a failure it frees what it read.
labelled_all :: proc(
	db: ^pq.Conn,
	allocator := context.allocator,
) -> (
	all: []Labelled_Row,
	err: pq.Error,
) {
	rows := labelled_open(db, allocator) or_return
	out := make([dynamic]Labelled_Row, allocator)
	for row in labelled_next(&rows) {
		append(&out, row)
	}
	if err = labelled_close(&rows); err != nil {
		labelled_free(out[:], allocator)
		return nil, err
	}
	return out[:], nil
}

// labelled_free_row frees the text and blobs of row, which are in allocator.
labelled_free_row :: proc(row: Labelled_Row, allocator := context.allocator) {
	delete(row.body, allocator)
	if v, ok := row.label.?; ok {
		delete(v, allocator)
	}
}

// labelled_free frees all, as labelled_all returns it, with every row's text and
// blobs.
labelled_free :: proc(all: []Labelled_Row, allocator := context.allocator) {
	for row in all {
		labelled_free_row(row, allocator)
	}
	delete(all, allocator)
}

@(private = "file")
BY_MOOD_SQL :: `SELECT mood, rank, count(*) AS "notes: i64"
FROM note GROUP BY ROLLUP (mood, rank)`

// By_Mood_Row is a row of by_mood. Text and blob fields are allocated in the
// allocator the query was given.
By_Mood_Row :: struct {
	mood:  Maybe(string), // Maybe: GROUPING SETS, ROLLUP or CUBE fill a grouped column with NULL
	rank:  Maybe(i32), // Maybe: GROUPING SETS, ROLLUP or CUBE fill a grouped column with NULL
	notes: i64, // annotated, not inferred
}

// By_Mood_Rows is a cursor over the rows of by_mood. err is what stopped it, once it
// is closed: a failed start, a failed step, or a value of the wrong type.
By_Mood_Rows :: struct {
	result: pq.Result,
	at:     int,
	err:    pq.Error,
}

// Notes counted by mood and rank, with ROLLUP's subtotals.
//
// by_mood is :many in queries.sql: by_mood_open as a guard. Written
// `if by_mood(&rows, db, ...) { for row in by_mood_next(&rows) { ... } }`, it closes
// the cursor at the end of the if and leaves what stopped it in rows.err,
// which a deferred close cannot return. It is false if the query cannot start.
@(deferred_in = by_mood_guard_close)
by_mood :: proc(
	rows: ^By_Mood_Rows,
	db: ^pq.Conn,
	allocator := context.allocator,
) -> bool {
	opened, err := by_mood_open(db, allocator)
	rows^ = opened
	rows.err = err
	return err == nil
}

@(private = "file")
by_mood_guard_close :: proc(
	rows: ^By_Mood_Rows,
	db: ^pq.Conn,
	allocator := context.allocator,
) {
	by_mood_close(rows)
}

// by_mood_open starts by_mood: step the cursor with by_mood_next and end it with
// by_mood_close. Text and blobs are allocated in allocator.
by_mood_open :: proc(
	db: ^pq.Conn,
	allocator := context.allocator,
) -> (
	rows: By_Mood_Rows,
	err: pq.Error,
) {
	rows.result = pq.exec_values(
		db,
		BY_MOOD_SQL,
		{},
		allocator,
	) or_return
	return
}

// by_mood_next reads the next row; ok is false at the end or on a failure.
by_mood_next :: proc(rows: ^By_Mood_Rows) -> (row: By_Mood_Row, ok: bool) {
	if rows.err != nil || rows.at >= len(rows.result.rows) {
		return
	}
	cells := rows.result.rows[rows.at]
	rows.at += 1
	row.mood = pq.read_exact_maybe(cells[0], "mood", string, &rows.err, rows.result.allocator)
	row.rank = pq.read_exact_maybe(cells[1], "rank", i32, &rows.err, rows.result.allocator)
	row.notes = pq.read_exact(cells[2], "notes", i64, &rows.err, rows.result.allocator)
	if rows.err != nil {
		by_mood_free_row(row, rows.result.allocator)
		return {}, false
	}
	return row, true
}

// by_mood_close ends the cursor and returns what stopped it, which it also
// keeps in rows.err. Closing twice is safe.
by_mood_close :: proc(rows: ^By_Mood_Rows) -> pq.Error {
	pq.destroy(&rows.result)
	return rows.err
}

// by_mood_all reads every row of by_mood into a slice in allocator, with their
// text and blobs; free it with by_mood_free. On a failure it frees what it read.
by_mood_all :: proc(
	db: ^pq.Conn,
	allocator := context.allocator,
) -> (
	all: []By_Mood_Row,
	err: pq.Error,
) {
	rows := by_mood_open(db, allocator) or_return
	out := make([dynamic]By_Mood_Row, allocator)
	for row in by_mood_next(&rows) {
		append(&out, row)
	}
	if err = by_mood_close(&rows); err != nil {
		by_mood_free(out[:], allocator)
		return nil, err
	}
	return out[:], nil
}

// by_mood_free_row frees the text and blobs of row, which are in allocator.
by_mood_free_row :: proc(row: By_Mood_Row, allocator := context.allocator) {
	if v, ok := row.mood.?; ok {
		delete(v, allocator)
	}
}

// by_mood_free frees all, as by_mood_all returns it, with every row's text and
// blobs.
by_mood_free :: proc(all: []By_Mood_Row, allocator := context.allocator) {
	for row in all {
		by_mood_free_row(row, allocator)
	}
	delete(all, allocator)
}

@(private = "file")
ADD_SQL :: `INSERT INTO note(body, attachment) VALUES ($1, $2) RETURNING id`

// Add_Row is a row of add. Text and blob fields are allocated in the
// allocator the query was given.
Add_Row :: struct {
	id: i64,
}

// add is :one in queries.sql.
add :: proc(
	db: ^pq.Conn,
	body: string,
	attachment: Maybe([]byte),
	allocator := context.allocator,
) -> (
	row: Add_Row,
	found: bool,
	err: pq.Error,
) {
	res := pq.exec_values(
		db,
		ADD_SQL,
		{body, pq.nullable(attachment)},
		allocator,
	) or_return
	defer pq.destroy(&res)
	if len(res.rows) > 1 {
		second := fmt.aprint("add is :one but returned a second row", allocator = allocator)
		return {}, false, pq.Fault{message = second}
	}
	if len(res.rows) == 0 {
		return
	}
	cells := res.rows[0]
	row.id = pq.read_exact(cells[0], "id", i64, &err, allocator)
	if err != nil {
		add_free_row(row, allocator)
		return {}, false, err
	}
	return row, true, nil
}

// add_free_row frees the text and blobs of row, which are in allocator.
add_free_row :: proc(row: Add_Row, allocator := context.allocator) {
}

@(private = "file")
RESCORE_SQL :: `UPDATE note SET score = $1, rank = rank + 1 WHERE id = $2`

// rescore is :rows in queries.sql.
rescore :: proc(
	db: ^pq.Conn,
	id: i64,
	score: f64,
	allocator := context.allocator,
) -> (
	n: i64,
	err: pq.Error,
) {
	res := pq.exec_values(
		db,
		RESCORE_SQL,
		{score, id},
		allocator,
	) or_return
	defer pq.destroy(&res)
	return i64(res.cmd_tuples), nil
}

@(private = "file")
LABEL_SQL :: `INSERT INTO label(note_id, name) VALUES ($1, $2) ON CONFLICT DO NOTHING`

// label is :exec in queries.sql.
label :: proc(
	db: ^pq.Conn,
	note_id: i64,
	name: string,
	allocator := context.allocator,
) -> pq.Error {
	res := pq.exec_values(
		db,
		LABEL_SQL,
		{note_id, name},
		allocator,
	) or_return
	pq.destroy(&res)
	return nil
}

@(private = "file")
UNPIN_ALL_SQL :: `UPDATE note SET pinned = false WHERE pinned`

// unpin_all is :rows in queries.sql.
unpin_all :: proc(
	db: ^pq.Conn,
	allocator := context.allocator,
) -> (
	n: i64,
	err: pq.Error,
) {
	res := pq.exec_values(
		db,
		UNPIN_ALL_SQL,
		{},
		allocator,
	) or_return
	defer pq.destroy(&res)
	return i64(res.cmd_tuples), nil
}

// check prepares every query against db and compares the parameters and
// columns each has there with those it was generated for, so a database
// whose schema has drifted from schema.sql fails when it is opened rather
// than when a query first runs.
check :: proc(db: ^pq.Conn, allocator := context.allocator) -> pq.Error {
	pq.check_statement(
		db,
		"note",
		NOTE_SQL,
		1,
		{"body", "pinned", "rank", "score", "price", "uid", "at", "mood", "attachment"},
		allocator,
	) or_return
	pq.check_statement(
		db,
		"totals",
		TOTALS_SQL,
		0,
		{"notes: i64", "score"},
		allocator,
	) or_return
	pq.check_statement(
		db,
		"labelled",
		LABELLED_SQL,
		0,
		{"id", "body", "label"},
		allocator,
	) or_return
	pq.check_statement(
		db,
		"by_mood",
		BY_MOOD_SQL,
		0,
		{"mood", "rank", "notes: i64"},
		allocator,
	) or_return
	pq.check_statement(
		db,
		"add",
		ADD_SQL,
		2,
		{"id"},
		allocator,
	) or_return
	pq.check_statement(
		db,
		"rescore",
		RESCORE_SQL,
		2,
		{},
		allocator,
	) or_return
	pq.check_statement(
		db,
		"label",
		LABEL_SQL,
		2,
		{},
		allocator,
	) or_return
	pq.check_statement(
		db,
		"unpin_all",
		UNPIN_ALL_SQL,
		0,
		{},
		allocator,
	) or_return
	return nil
}
