// Code generated by jm-sqlgen from schema.sql and queries.sql. DO NOT EDIT.

package notes_pg_queries

import "core:log"
import "core:strings"
import "core:testing"

import "jm:pq"
import "jm:pq/testdb"

@(private = "file")
Sqlgen_Set :: struct {
	name:   string,
	seed:   string,
	int_v:  i64,
	real_v: f64,
	text_v: string,
	blob_v: string,
	bool_v: bool,
	nulls:  bool,
}

// SQLGEN_SETS are the database states every query runs against: nothing at
// all, which empties aggregates and subqueries; every nullable column NULL;
// the extremes of each type; and each table alone, which leaves the other
// side of an outer join missing.
// high: note.price holds the base value, since note refused the set's own: numeric field overflow.
@(private = "file")
SQLGEN_SETS := [?]Sqlgen_Set {
	{
		name = "empty",
		seed = ``,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = false,
	},
	{
		name = "nulls",
		seed = `INSERT INTO "public"."label"("note_id", "name")
VALUES ('1', 'a');
INSERT INTO "public"."note"("body", "pinned", "rank", "score", "price", "uid", "at", "mood", "attachment")
VALUES ('a', 't', '1', '1.5', NULL, '00000000-0000-0000-0000-000000000001', '2000-01-01 00:00:00+00', 'calm', NULL);
`,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = true,
	},
	{
		name = "low",
		seed = `INSERT INTO "public"."label"("note_id", "name")
VALUES ('-9223372036854775808', '');
INSERT INTO "public"."note"("body", "pinned", "rank", "score", "price", "uid", "at", "mood", "attachment")
VALUES ('', 'f', '-2147483648', '-1.5', '-1.5', '00000000-0000-0000-0000-000000000000', '1970-01-01 00:00:00+00', 'calm', '\x');
`,
		int_v = -9223372036854775808,
		real_v = -1.5,
		text_v = ``,
		blob_v = ``,
		bool_v = false,
		nulls = false,
	},
	{
		name = "high",
		seed = `INSERT INTO "public"."label"("note_id", "name")
VALUES ('9223372036854775807', 'zß€😀');
INSERT INTO "public"."note"("body", "pinned", "rank", "score", "price", "uid", "at", "mood", "attachment")
VALUES ('zß€😀', 't', '2147483647', '1e+300', '1.5', 'ffffffff-ffff-ffff-ffff-ffffffffffff', '9999-12-31 23:59:59+00', 'done', '\x00ff');
`,
		int_v = 9223372036854775807,
		real_v = 1e+300,
		text_v = `zß€😀`,
		blob_v = "\x00\xff",
		bool_v = true,
		nulls = false,
	},
	{
		name = "only_label",
		seed = `INSERT INTO "public"."label"("note_id", "name")
VALUES ('1', 'a');
`,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = true,
	},
	{
		name = "only_note",
		seed = `INSERT INTO "public"."note"("body", "pinned", "rank", "score", "price", "uid", "at", "mood", "attachment")
VALUES ('a', 't', '1', '1.5', NULL, '00000000-0000-0000-0000-000000000001', '2000-01-01 00:00:00+00', 'calm', NULL);
`,
		int_v = 1,
		real_v = 1.5,
		text_v = `a`,
		blob_v = `a`,
		bool_v = true,
		nulls = true,
	},
}

// Each query runs in every data set through its generated proc, which
// checks every value it reads against the type it was generated with. check
// runs too, against the schema as the server holds it.
@(test)
sqlgen_queries_hold_their_types :: proc(t: ^testing.T) {
	context.allocator = context.temp_allocator
	if ok, why := testdb.start(); !ok {
		log.warnf("skipped, no PostgreSQL server to test against: %s", why)
		return
	}
	db, err := pq.connect()
	if !testing.expect_value(t, err, nil) {
		return
	}
	defer pq.close(db)
	for set in SQLGEN_SETS {
		sqlgen_exec(t, db, "BEGIN")
		// A data set's child rows have no parents; see jm-sqlgen's PG_NO_FOREIGN_KEYS.
		sqlgen_exec(t, db, "SET LOCAL session_replication_role = replica")
		sqlgen_exec(t, db, #load("schema.sql", string))
		if set.seed != "" {
			sqlgen_exec(t, db, set.seed)
		}
		testing.expect_value(t, check(db), nil)
		sqlgen_run(t, db, set)
		sqlgen_exec(t, db, "ROLLBACK")
	}
}

@(private = "file")
sqlgen_run :: proc(t: ^testing.T, db: ^pq.Conn, set: Sqlgen_Set) {
	{
		sqlgen_begin(t, db)
		_, _, err := note(db, sqlgen_int(set, i64))
		sqlgen_end(t, db, set, "note", err)
	}
	{
		sqlgen_begin(t, db)
		_, _, err := totals(db)
		sqlgen_end(t, db, set, "totals", err)
	}
	{
		sqlgen_begin(t, db)
		rows, err := labelled_open(db)
		if err == nil {
			for _ in labelled_next(&rows) {
			}
			err = labelled_close(&rows)
		}
		sqlgen_end(t, db, set, "labelled_open", err)
	}
	{
		sqlgen_begin(t, db)
		rows: Labelled_Rows
		if labelled(&rows, db) {
			for _ in labelled_next(&rows) {
			}
		}
		sqlgen_end(t, db, set, "labelled", rows.err)
	}
	{
		sqlgen_begin(t, db)
		_, err := labelled_all(db)
		sqlgen_end(t, db, set, "labelled_all", err)
	}
	{
		sqlgen_begin(t, db)
		rows, err := by_mood_open(db)
		if err == nil {
			for _ in by_mood_next(&rows) {
			}
			err = by_mood_close(&rows)
		}
		sqlgen_end(t, db, set, "by_mood_open", err)
	}
	{
		sqlgen_begin(t, db)
		rows: By_Mood_Rows
		if by_mood(&rows, db) {
			for _ in by_mood_next(&rows) {
			}
		}
		sqlgen_end(t, db, set, "by_mood", rows.err)
	}
	{
		sqlgen_begin(t, db)
		_, err := by_mood_all(db)
		sqlgen_end(t, db, set, "by_mood_all", err)
	}
	{
		sqlgen_begin(t, db)
		_, _, err := add(db, set.text_v, sqlgen_maybe(transmute([]byte)set.blob_v, set.nulls))
		sqlgen_end(t, db, set, "add", err)
	}
	{
		sqlgen_begin(t, db)
		_, err := rescore(db, sqlgen_int(set, i64), sqlgen_real(set, f64))
		sqlgen_end(t, db, set, "rescore", err)
	}
	{
		sqlgen_begin(t, db)
		err := label(db, sqlgen_int(set, i64), set.text_v)
		sqlgen_end(t, db, set, "label", err)
	}
	{
		sqlgen_begin(t, db)
		_, err := unpin_all(db)
		sqlgen_end(t, db, set, "unpin_all", err)
	}
}

@(private = "file")
sqlgen_maybe :: proc(v: $T, null: bool) -> Maybe(T) {
	if null {
		return nil
	}
	return v
}

// sqlgen_int is the set's integer as T, held to T's range, so the extremes
// of the set are the extremes of each width.
@(private = "file")
sqlgen_int :: proc(set: Sqlgen_Set, $T: typeid) -> T {
	return T(clamp(set.int_v, i64(min(T)), i64(max(T))))
}

// sqlgen_real is the set's float as T, held to T's finite range.
@(private = "file")
sqlgen_real :: proc(set: Sqlgen_Set, $T: typeid) -> T {
	return T(clamp(set.real_v, -f64(max(T)), f64(max(T))))
}

@(private = "file")
sqlgen_exec :: proc(t: ^testing.T, db: ^pq.Conn, sql: string, loc := #caller_location) {
	res, err := pq.exec(db, sql)
	testing.expect_value(t, err, nil, loc = loc)
	pq.destroy(&res)
}

@(private = "file")
sqlgen_begin :: proc(t: ^testing.T, db: ^pq.Conn) {
	sqlgen_exec(t, db, "SAVEPOINT sqlgen")
}

// sqlgen_end undoes what the query changed, and fails the test unless the
// query succeeded or the data set's values broke a constraint or a range,
// SQLSTATE classes 23 and 22. A value read as the wrong type is neither.
@(private = "file")
sqlgen_end :: proc(t: ^testing.T, db: ^pq.Conn, set: Sqlgen_Set, query: string, err: pq.Error) {
	sqlgen_exec(t, db, "ROLLBACK TO SAVEPOINT sqlgen")
	sqlgen_exec(t, db, "RELEASE SAVEPOINT sqlgen")
	f, failed := err.(pq.Fault)
	if !failed {
		return
	}
	data := strings.has_prefix(f.sqlstate, "22") || strings.has_prefix(f.sqlstate, "23")
	testing.expectf(t, data, "data set %s: %s: %s %s", set.name, query, f.sqlstate, f.message)
}
