// Generated from accesskit-c 0.23.1's include/accesskit.h by the enum
// extractor in the session that landed the bridge: each enum in the
// header's order, since the values cross the C boundary by position.
// Regenerate rather than edit when the pinned release changes.
package accesskit

Role :: enum u8 {
	Unknown,
	Text_Run,
	Cell,
	Label,
	Image,
	Link,
	Row,
	List_Item,
	List_Marker,
	Tree_Item,
	List_Box_Option,
	Menu_Item,
	Menu_List_Option,
	Paragraph,
	Generic_Container,
	Check_Box,
	Radio_Button,
	Text_Input,
	Button,
	Default_Button,
	Pane,
	Row_Header,
	Column_Header,
	Row_Group,
	List,
	Table,
	Layout_Table_Cell,
	Layout_Table_Row,
	Layout_Table,
	Switch,
	Menu,
	Multiline_Text_Input,
	Search_Input,
	Date_Input,
	Date_Time_Input,
	Week_Input,
	Month_Input,
	Time_Input,
	Email_Input,
	Number_Input,
	Password_Input,
	Phone_Number_Input,
	Url_Input,
	Abbr,
	Alert,
	Alert_Dialog,
	Application,
	Article,
	Audio,
	Banner,
	Blockquote,
	Canvas,
	Caption,
	Caret,
	Code,
	Color_Well,
	Combo_Box,
	Editable_Combo_Box,
	Complementary,
	Comment,
	Content_Deletion,
	Content_Insertion,
	Content_Info,
	Definition,
	Description_List,
	Details,
	Dialog,
	Disclosure_Triangle,
	Document,
	Embedded_Object,
	Emphasis,
	Feed,
	Figure_Caption,
	Figure,
	Footer,
	Form,
	Grid,
	Grid_Cell,
	Group,
	Header,
	Heading,
	Iframe,
	Iframe_Presentational,
	Ime_Candidate,
	Keyboard,
	Legend,
	Line_Break,
	List_Box,
	Log,
	Main,
	Mark,
	Marquee,
	Math,
	Menu_Bar,
	Menu_Item_Check_Box,
	Menu_Item_Radio,
	Menu_List_Popup,
	Meter,
	Navigation,
	Note,
	Plugin_Object,
	Progress_Indicator,
	Radio_Group,
	Region,
	Root_Web_Area,
	Ruby,
	Ruby_Annotation,
	Scroll_Bar,
	Scroll_View,
	Search,
	Section,
	Section_Footer,
	Section_Header,
	Slider,
	Spin_Button,
	Splitter,
	Status,
	Strong,
	Suggestion,
	Svg_Root,
	Tab,
	Tab_List,
	Tab_Panel,
	Term,
	Time,
	Timer,
	Title_Bar,
	Toolbar,
	Tooltip,
	Tree,
	Tree_Grid,
	Video,
	Web_View,
	Window,
	Pdf_Actionable_Highlight,
	Pdf_Root,
	Graphics_Document,
	Graphics_Object,
	Graphics_Symbol,
	Doc_Abstract,
	Doc_Acknowledgements,
	Doc_Afterword,
	Doc_Appendix,
	Doc_Back_Link,
	Doc_Biblio_Entry,
	Doc_Bibliography,
	Doc_Biblio_Ref,
	Doc_Chapter,
	Doc_Colophon,
	Doc_Conclusion,
	Doc_Cover,
	Doc_Credit,
	Doc_Credits,
	Doc_Dedication,
	Doc_Endnote,
	Doc_Endnotes,
	Doc_Epigraph,
	Doc_Epilogue,
	Doc_Errata,
	Doc_Example,
	Doc_Footnote,
	Doc_Foreword,
	Doc_Glossary,
	Doc_Gloss_Ref,
	Doc_Index,
	Doc_Introduction,
	Doc_Note_Ref,
	Doc_Notice,
	Doc_Page_Break,
	Doc_Page_Footer,
	Doc_Page_Header,
	Doc_Page_List,
	Doc_Part,
	Doc_Preface,
	Doc_Prologue,
	Doc_Pullquote,
	Doc_Qna,
	Doc_Subtitle,
	Doc_Tip,
	Doc_Toc,
	List_Grid,
	Terminal,
}

Action :: enum u8 {
	Click,
	Focus,
	Blur,
	Collapse,
	Expand,
	Custom_Action,
	Decrement,
	Increment,
	Hide_Tooltip,
	Show_Tooltip,
	Replace_Selected_Text,
	Scroll_Down,
	Scroll_Left,
	Scroll_Right,
	Scroll_Up,
	Scroll_Into_View,
	Scroll_To_Point,
	Set_Scroll_Offset,
	Set_Text_Selection,
	Set_Sequential_Focus_Navigation_Starting_Point,
	Set_Value,
	Show_Context_Menu,
}

Toggled :: enum u8 {
	False,
	True,
	Mixed,
}

// Invalid is why a node's value is invalid (accesskit's Invalid); jm:ui
// sets only True.
Invalid :: enum u8 {
	True,
	Grammar,
	Spelling,
}

// Aria_Current is accesskit_aria_current (accesskit.h 0.23.1, lines
// 152-166): which item of a set is the current one, and of what kind.
Aria_Current :: enum u8 {
	False,
	True,
	Page,
	Step,
	Location,
	Date,
	Time,
}

Live :: enum u8 {
	Off,
	Polite,
	Assertive,
}

// Sort_Direction is accesskit_sort_direction (accesskit's SortDirection):
// how a column header's column is sorted.
Sort_Direction :: enum u8 {
	Ascending,
	Descending,
	Other,
}
